---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: ${EXT_AUTH_APP:-${APP}}
spec:
  extAuth:
    failOpen: false
    headersToExtAuth:
      - x-forwarded-proto
      - x-forwarded-host
      - cookie
      - authorization
    http:
      backendRefs:
        - name: ak-outpost-proxy
          namespace: security
          port: 9000
      headersToBackend:
        - set-cookie
        - authorization
        - location
        - x-authentik-username
        - x-authentik-groups
        - x-authentik-email
        - x-authentik-name
        - x-authentik-uid
      path: /outpost.goauthentik.io/auth/envoy
  targetRefs:
    - group: ${EXT_AUTH_TARGET_GROUP:-gateway.networking.k8s.io}
      kind: ${EXT_AUTH_TARGET_KIND:-HTTPRoute}
      name: ${EXT_AUTH_TARGET_NAME:-${APP}}
