---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: ${EXT_AUTH_APP:-${APP}}
spec:
  extAuth:
    failOpen: false
    headersToExtAuth:
      - X-Forwarded-Proto
      - cookie
    http:
      backendRefs:
        - name: authentik-outpost-proxy
          namespace: security
          port: 9000
      headersToBackend:
        - authorization
        - Set-Cookie
        - X-authentik-email
        - X-authentik-entitlements
        - X-authentik-groups
        - X-authentik-meta-app
        - X-authentik-meta-outpost
        - X-authentik-meta-provider
        - X-authentik-meta-version
        - X-authentik-name
        - X-authentik-uid
        - X-authentik-username
        - X-forwarded-host
      path: /outpost.goauthentik.io/auth/envoy
  targetRefs:
    - group: ${EXT_AUTH_TARGET_GROUP:-gateway.networking.k8s.io}
      kind: ${EXT_AUTH_TARGET_KIND:-HTTPRoute}
      name: ${EXT_AUTH_TARGET_NAME:-${APP}}
