apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-config
  namespace: flux-system
spec:
  # This is the crucial part
  dependsOn:
    - name: metallb-app
  interval: 15m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./cluster/apps/core/metallb/config
  prune: true


apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: main-pool
  namespace: metallb-system
spec:
  addresses:
    - 10.1.20.200-10.1.20.220
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: main-l2
  namespace: metallb-system
spec:
  ipAddressPools:
    - main-pool