apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
    name: homelab-wildcard-cert
    namespace: cert-manager
spec:
    secretName: homelab-wildcard-tls
    issuerRef:
        name: letsencrypt-dns-namecheap
        kind: ClusterIssuer
    dnsNames:
        - '*.taylan.dev'
        - taylan.dev
