---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pushgateway
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: pushgateway
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    fullnameOverride: pushgateway
    namespaceOverride: observability

    serviceMonitor:
      enabled: true
      namespace: observability
      honorLabels: true

    persistentVolume:
      enabled: false

    securityContext:
      runAsNonRoot: true
      runAsUser: 65534
      runAsGroup: 65534
    containerSecurityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop:
          - ALL
      seccompProfile:
        type: RuntimeDefault

    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        memory: 64Mi
