apiVersion: v1
kind: Secret
metadata:
    name: namecheap-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:vD2yUU1QGkbL5/3/oY4Fb+aS8gr5Up5eSQht7pxaA2I=,iv:PYF+0CnhwQdl7RcGfsAmsKg8fjEaTdu6G9Q9ZeC5byU=,tag:lOfujHxZkxwibfwjDhdTEA==,type:str]
sops:
    age:
        - recipient: age1xlls984taykl6jyq0f965lyx66qj6e4cg4wqwrfav258c5gpr44qkwuv3w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1ak16bjJyczVwL3lwYUtF
            dUdSZ2RkSnlYZk5ubzZPZTdoamVsckxXK25nClpaTTBWL1U2VjN0RHBpT0tKT0h4
            MVRoRmVPK2hvUGxWTHJyVkRDdjhFVUEKLS0tIFNRS2pXaDdQakN5eXRLMUNiWG44
            UnlHYmJod3B5N0h1bDhrbVR6L1lRZlUKD5QGVR8J3GhHDMQDUey0dKfew0PXNyHu
            d5mmxNrSZT9yE3GU0/RuGwkSaR9XC1Sbif6ojIxxIb6CebDeS6Awig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-12T00:52:57Z"
    mac: ENC[AES256_GCM,data:t30VxXR0fj0ThuD9ax2FTpntTnrvpI0WiehYcXWPkWioYQVwscBV53oBQncy4jXnVHtAZSYl5KprAwyesYmIkBuISlLtDVXau78HZkuFYz3hSOVDxVoXt59KaZWSa8F7IlpgZMDNUYMlTTcvEScJbWzcPaSiAUqCKZg3Ujw3ucE=,iv:saC7zy+w+NW+6EYwTB4kCMjnCBFHvyVXTkFDKT9IcJ4=,tag:xsWORsiD1JktC+sO5XOcLA==,type:str]
    encrypted_regex: ^(data|stringData|((?i).*(API_KEY|TOKEN|SECRET|USERNAME|EMAIL|ZONES).*))$
    version: 3.10.2
