apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-app
  namespace: flux-system
spec:
  interval: 15m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./clusters/infrastructure/apps/core/cert-manager
  prune: true
  wait: true
  patches:
    - patch: |
        apiVersion: kustomize.config.k8s.io/v1beta1
        kind: Kustomization
        resources:
        - namespace.yaml
        - helmrelease.yaml
      target:
        kind: Kustomization
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-config
  namespace: flux-system
spec:
  dependsOn:
    - name: cert-manager-app
  interval: 15m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./clusters/infrastructure/apps/core/cert-manager
  prune: true
  patches:
    - patch: |
        apiVersion: kustomize.config.k8s.io/v1beta1
        kind: Kustomization
        resources:
        - namecheap-secret.yaml
        - clusterissuer.yaml
      target:
        kind: Kustomization