---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: gateway-api-crds
spec:
  interval: 30m
  url: https://github.com/kubernetes-sigs/gateway-api
  ref:
    # renovate: depName=kubernetes-sigs/gateway-api datasource=github-releases
    tag: v1.3.0
  ignore: |
      # exclude
      /*
      # include
      !config/crd/experimental/gateway*.yaml
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &name gateway-api-crds
  namespace: &namespace network
spec:
  targetNamespace: *namespace
  prune: true
  sourceRef:
    kind: GitRepository
    name: *name
  interval: 1h
  retryInterval: 2m
  timeout: 5m
  wait: true
