---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: freshrss
spec:
  dependsOn:
    - name: longhorn
      namespace: longhorn-system
  interval: 1h
  path: ./infrastructure/apps/selfhosted/freshrss/app
  postBuild:
    substitute:
      APP: freshrss
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: selfhosted
  wait: false
