---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: loki
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 6.53.0
  url: oci://ghcr.io/grafana/helm-charts/loki
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
spec:
  interval: 15m
  chartRef:
    kind: OCIRepository
    name: loki
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    deploymentMode: SingleBinary
    lokiCanary:
      enabled: false
    test:
      enabled: false
    chunksCache:
      enabled: false
    resultsCache:
      enabled: false
    loki:
      auth_enabled: false
      analytics:
        reporting_enabled: false
      commonConfig:
        replication_factor: 1
        ring:
          kvstore:
            store: inmemory

      schemaConfig:
        configs:
          - from: "2024-04-01"
            store: tsdb
            object_store: filesystem
            schema: v13
            index:
              prefix: loki_index_
              period: 24h

      storage:
        type: filesystem

      limits_config:
        retention_period: 14d
        allow_structured_metadata: true
      ingester:
        chunk_encoding: snappy
      tracing:
        enabled: true

      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 1000m
          memory: 1Gi

      persistence:
        enabled: true
        storageClassName: longhorn
        size: 10Gi
    singleBinary:
      replicas: 1

    backend:
      replicas: 0
    read:
      replicas: 0
    write:
      replicas: 0
