---
area/bootstrap:
  - changed-files:
      - any-glob-to-any-file: "provision**/*"
area/docs:
  - changed-files:
      - any-glob-to-any-file:
          - "README.md"
area/github:
  - changed-files:
      - any-glob-to-any-file: ".github/**/*"
area/infrastructure:
  - changed-files:
      - any-glob-to-any-file: "infrastructure/**/*"
