---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: envoy-gateway
  namespace: envoy-gateway-system
spec:
  interval: 1h
  chart:
    spec:
      chart: gateway
      version: "v1.4.1"
      sourceRef:
        kind: OCIRepository
        name: envoy-gateway
        namespace: flux-system
  install:
    remediation:
      retries: -1
    crds: CreateReplace
  upgrade:
    cleanupOnFail: true
    disableHooks: false
    remediation:
      retries: 3
    crds: CreateReplace
