apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: envoy-gateway
  namespace: envoy-gateway-system
spec:
  interval: 10m
  chart:
    spec:
      chart: gateway-helm
      version: v1.4.2
      sourceRef:
        kind: HelmRepository
        name: envoy-gateway
        namespace: flux-system
  install:
    remediation:
      retries: -1
    crds: CreateReplace
  upgrade:
    cleanupOnFail: true
    disableHooks: false
    remediation:
      retries: 3
    crds: CreateReplace
  values:
    service:
      type: LoadBalancer
      annotations:
        metallb.universe.tf/address-pool: default
