---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: envoy-gateway
  namespace: envoy-gateway-system
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 1.4.2
  url: oci://docker.io/envoyproxy/gateway-helm

---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: eg
  namespace: envoy-gateway-system
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: envoy-gateway
  install:
    disableHooks: false
    remediation:
      retries: -1
    crds: CreateReplace
  upgrade:
    cleanupOnFail: true
    disableHooks: false
    remediation:
      retries: 3
    crds: CreateReplace
  values:
    service:
      type: LoadBalancer
      annotations:
        metallb.universe.tf/address-pool: default
