---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app eg
  namespace: &namespace envoy-gateway-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
      - ../../../components/common
  interval: 1h
  path: ./infrastructure/apps/core/envoy-gateway/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 10m
  wait: false
