---
doublestar: true
exclude:
  - "**/*.sops.yaml"
formatter:
  indent: 2
  type: basic
  disable_alias_key_correction: true
  drop_merge_tag: true
  eof_newline: true
  force_array_style: block
  force_quote_style: double
  include_document_start: true
  line_ending: lf
  retain_line_breaks_single: true
  scan_folded_as_literal: true
  trim_trailing_whitespace: true
