apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cilium/
  - metallb/
  - cert-manager/
  - gateway-api/
  - reflector/
  - victoria-metrics/
  - longhorn/
  - loki/
  - promtail/
  - tempo/
  - grafana/
  - metric-scraper/
