apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: letsencrypt-prod
spec:
    acme:
        server: https://acme-v02.api.letsencrypt.org/directory
        email: ENC[AES256_GCM,data:6RQbvdmVHfP/TrqjbIv+E3HMQno=,iv:jV+5LBdj+tbJxI65etvDsYEcxEo6hDxD1AT8dSo6RyU=,tag:MXToNXGaKPdbAo3EUCnBBQ==,type:str]
        privateKeySecretRef:
            name: ENC[AES256_GCM,data:46PeQgLDxYWFvn/660ljHQ==,iv:fmHFxjFwZMurkFa0yWMMAKvphiNvCi2/f6ihQsuE3J4=,tag:wlmklFsfMAf9BYPbYQbfhg==,type:str]
        solvers:
            - dns01:
                namecheap:
                    username: ENC[AES256_GCM,data:ES400rkgbpY=,iv:f02/PXKs0VvljdY4LOgX4r4YSJ0bcKR0cra1/6LDR3Q=,tag:zQ0sELg80Nd0qX/SMpmh+g==,type:str]
                    apiKeySecretRef:
                        name: ENC[AES256_GCM,data:j8kyyH9r+57mdfzvvFtudpI=,iv:vf494lCR9L2LJR1HsXmRd8+FCePs2Lqu1ZlUzvCeGNE=,tag:t+ttYLsfGL8lkr7zBkC4hg==,type:str]
                        key: ENC[AES256_GCM,data:dDil7x/ebg==,iv:M6TWlODV7Z2chXKwNSz0IndF3a0mlXxowP4GJ2C18rE=,tag:EPOLximmGKGrFuIeJiGguA==,type:str]
    selector:
        dnsZones:
            - ENC[AES256_GCM,data:P5e9+V5i89IB+uCF8EWXApHxyTeCSTJZ,iv:lkeMt07A2U4zegWRjgH3v1m2j5qidGkIeZ1yVgZ9X2g=,tag:uSZ6SfltNUlM0VlUJ/YqaQ==,type:str]
sops:
    age:
        - recipient: age1xlls984taykl6jyq0f965lyx66qj6e4cg4wqwrfav258c5gpr44qkwuv3w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCclRwcGd3K3ZQczBhK2Fu
            SXZIeDRvUmhuRjd5YmoxdU04L0NkV0NTRkJJCk9PUkRXb24vek54Z3JJYnRYNks5
            cVI3OWJkN1MxMkhlc3d6alZob1pIZ1EKLS0tIHA0Sk55aFY4Qis3MVoxTmpmYzl6
            eVdsVU4yU21XVll0d2V4cC9sYkk4R1UKawlSFJd7I0MZuFuphxq8zYsMj8kXYsVq
            10gLSamtJbrIXx3x8aHYpyLttQPVOR4aP8R2A47ZJ6hE0OPt32QCiQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-12T00:52:49Z"
    mac: ENC[AES256_GCM,data:vFvdzMlx9IOFMj+TPf807keNKGrP+ZGp3pj0PC4fLVKdLtmNm4JrIlUy6IHmghl9CX9xwhdTjZCcjqFXcgNtFlkV5rMiBTAxZqJTdd/FaUKBqTFpwBZQXG7v0d5ux9j8K124eum2vPkv7ogWs+GUQaVs85r8S/8r4KomZOGB5Ag=,iv:CK/p6YmJ7AY/Txu100PulFy9oo00eMH3/R4lLLq4Hkk=,tag:7kO6/1RrIuY8i4ma4/Yc/w==,type:str]
    encrypted_regex: ^(data|stringData|((?i).*(API_KEY|TOKEN|SECRET|USERNAME|EMAIL|ZONES).*))$
    version: 3.10.2
