apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
stringData:
    admin-user: ENC[AES256_GCM,data:z1ChT1ZU,iv:FAVwAaCJUU3OC+8lfCRqKDbzgfxTebAMNwoL5LhEbUM=,tag:A81xP0aVoluMEBO1LHjJjw==,type:str]
    admin-password: ENC[AES256_GCM,data:+3xwHDdh9WKYZQ==,iv:CSJ7/Cwz5GPtp6DjbcSAqj7LbpCNrD3zZ4BHqqdhIpc=,tag:BALK9EiSmfDzjxDudctBrQ==,type:str]
sops:
    age:
        - recipient: age1xlls984taykl6jyq0f965lyx66qj6e4cg4wqwrfav258c5gpr44qkwuv3w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsRDRYNXp0aFI1Nm15ZmVv
            dGh1NWRkdXVmMU5sWnpaL0ovVVZsTjFhR1hZCjl6dkRWcUc0cUFtYW9sOVkvcngv
            U0d0aElESHI4bEJVc3BWMTdyWUI1cTAKLS0tIHdzL3FnanhxMlRhdmJSa2hQU1Zy
            SVNLUnV3b2FCZnhTNnpBMDRnamxyV2MKxFjw8VqLeFbXYTnPVl36CRTQUik8YfIr
            81K4vmnRQdunsioMv8PZnKf9a+MEcHTvcXHRgjQFWG5PASPxtw9oJA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-04T13:35:28Z"
    mac: ENC[AES256_GCM,data:5e69pwPR32Nhs1t+k39Jz7JeCIAgb19Q7+cjEPwHFvyTDaWi2HhCqdDeG3tUU/66REygAilnGbLUosZ0AIHi/nA8+tpmeiNgQPJqwn3xbCU1PJEaAqlinfWq3xzaEIBE1cfwnQxQcYGDy4Eo/E1d8GN+AkHawJ2P45cdVQev2pA=,iv:xmfP9p0XhQlKO69OZEeS+0g5upRNlpQmhdwyLi+//fQ=,tag:nTbJOkaLQNTXOz2l20pZ1Q==,type:str]
    encrypted_regex: ^(data|stringData|((?i).*(API_KEY|TOKEN|SECRET|USER|EMAIL|ZONES|DNSNAMES|CLIENTIP).*))$
    version: 3.10.2
