apiVersion: v1
kind: Secret
metadata:
    name: grafana-oidc
stringData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:wUU/1ZSer6DUbj1K2e5DfykCvuksQOOnxzF/iknRuKJ80C1KODU0oQ==,iv:8E+b+w6ZKZiNzzkrvL1wTpFJJo5P/t2igE8vNg3ZSs0=,tag:YUiTaEeq6scJ6wm3ENr9FQ==,type:str]
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:TxZR7SeuvVLu1uX7kTHjsnJeXqn2fdQZ7Y3bPJA9QFVD7itn2JH3pTFjb4Ka7e0pgZ1ZyXFLhqo3rZi7alfXAeoJwVCTGbFAlU5ex3+BUtsCAiOgVmEVk87t/v4woUA6RfgCGxsuzUF2zXFEF02PUVWO6REAItH31nge5AQaFOo=,iv:j8kZVGfMWveDnWXSUXL9xUzLDARbpgI7hFLxJZL6THw=,tag:YHEc/3uxSWrzDvzitiqamQ==,type:str]
    GF_AUTH_GENERIC_OAUTH_NAME: ENC[AES256_GCM,data:E8DykuU0gjyU,iv:RIZ1/4Mw/zCEw211/ExRts1VBt9GxxiLPEIWIU8dy7E=,tag:G/FBaFruq6i7GY64RTySiA==,type:str]
    GF_AUTH_GENERIC_OAUTH_SCOPES: ENC[AES256_GCM,data:pC8jDINAewC8Lozmubh0Frw6HKk=,iv:NaKe+gg2V8ev84h50fuGxp9+T4haAstKbpBB/qhwV94=,tag:17QFZoCqj+6ki0IJOcOYYQ==,type:str]
    GF_AUTH_GENERIC_OAUTH_AUTH_URL: ENC[AES256_GCM,data:G+dgg/ww3SCqXl769hDVWJ4k6YNmOOoNQEIEbcO5+uBLprdf1ibPogakVBQdTjHRGuXte06FYUI=,iv:NyvKpgRwS7nd4+CXE8Kip76llTj1CmJo1gQP2Jd6dxo=,tag:fj1Fkr7KG+eVeYeo/Y/txA==,type:str]
    GF_AUTH_GENERIC_OAUTH_TOKEN_URL: ENC[AES256_GCM,data:p+XgDr67NaKcqWK4pZBILo9dTcupF2WSpYCN3eCKzdaw6nYEbXBg7zoaZqCMMHiBJCdghQ==,iv:dovo4G6C67BiyyWcL9mUQ7U6M2niigvTZrRfDpU/aPA=,tag:EjalfVD5xGRUt2wh6bfl5g==,type:str]
    GF_AUTH_GENERIC_OAUTH_API_URL: ENC[AES256_GCM,data:PcKM3t97nJGvcFZOWzi1QmB2lH2qv7pm2r+cS5NeSMCoprsYzROqjsS5CccePRU=,iv:mkuxyqXQhgtBMCZbgZLZ4wuzFH9HG2M2t/qlx2jfHnU=,tag:EUB+yIH2CHGJHLuzk1IQUA==,type:str]
    GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH: ENC[AES256_GCM,data:PPcmjJeGxSNeLbcQZ8ySLsq3GGNXHBhpn0LVNFeUrp7E/xJj025+vywo+96OaZu1TDlKvObbRKZuBr49,iv:9rw/LX/1R7ngFyva3h1aEg8y8I20WLwBR2KnDiovnRY=,tag:SHgMuIwja0C20gSg9qfK1w==,type:str]
sops:
    age:
        - recipient: age1xlls984taykl6jyq0f965lyx66qj6e4cg4wqwrfav258c5gpr44qkwuv3w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTM1NQbStDY3NSbTMxZ2VM
            SVVkM0N0Q20wdFFwOXhjakUwRlJCN05PeW44CldYNCtQejFOM2Nnc2s1T3J1VE1q
            UGdYNHkweEllZFlvdHFWeTRzTkdpVlUKLS0tIDBOZUdVQXNNbHdtcVpUbTJVWUpT
            czQxMnE3QzcwNFd2U01QbitadjYwM0UKbK22rbdTF2GhDPD7coHhxY1ZC849bA8W
            z2w5sl2xPjoXdsq+jVp6x4n7xNXD1swlvnXIYHMDq+BVeBYAXYcqEQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-17T20:23:15Z"
    mac: ENC[AES256_GCM,data:0YGzbnTCBVTYeyNRq36OVLLEkUgqRsTmL3Eg2xr/7Oov12VTe6GODDg8aAR7jppbd0k/xZpjr0g7CGCYdUjvih23pmUaakz6YwL5zBfrBQq0je+/yXk3Z40yHh8Ce4+83sb/ENNFuC9M+jn1+SIpbj0HFu6HEfC3MJuMTPSLT3o=,iv:IWJ5FYnBc6RAbbgiNJ4H0AqIN6CRud6IWNXQJGaC0j0=,tag:+QHhfCWZwJ64auCgiT9YNw==,type:str]
    encrypted_regex: ^(data|stringData|((?i).*(API_KEY|TOKEN|SECRET|USER|EMAIL|ZONES|DNSNAMES|CLIENTIP).*))$
    version: 3.12.2
