---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: authentik
spec:
  from:
    - &policy
      group: gateway.envoyproxy.io
      kind: SecurityPolicy
      namespace: selfhosted
    - <<: *policy
      namespace: media-center
    - <<: *policy
      namespace: observability
    - <<: *policy
      namespace: kube-system
  to:
    - group: ""
      kind: Service
      name: ak-outpost-proxy
