apiVersion: v1
kind: Secret
metadata:
    name: authentik-secret
stringData:
    #ENC[AES256_GCM,data:ug7F8A==,iv:1iv0XcErvdvwhqi4TFn/TL9jevqAfEfPsDysHRLHdP4=,tag:KBJ6JDkQ2GnL7XT7xy/JAg==,type:comment]
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:fyzmGkAOlYfsnJCoEoFAMEl0ZYBKNaeC8pXI0GbTv7ucR599YRL6SeY6tbg=,iv:eTwAKiThkV0CcSySvJkJohNLaGrAXGhwsGSL21Bt+qg=,tag:w6qz5EOA4aqVCjD0vl6sRA==,type:str]
    NEW_AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:aGdB/n4Aj8y6lcTdt15FRFKjG9UrMuMAtaxtXz9UjNs5kMAdpeFzxhBtpOYbvQXgrYyXg0MzZJETVlCPY1GJsXruvTg=,iv:WJ4ooTN2XNLaniBoVNxb4jAmIu/G1VW8jaElvEZHnz0=,tag:9FQ2WH+hyDomt6ffPv4Mng==,type:str]
    AUTHENTIK_DISABLE_UPDATE_CHECK: ENC[AES256_GCM,data:P9at8A==,iv:aYPBYh2V/JBLilK0rP0Y5oLbzzR7PgGYKQsLbqFAu8Y=,tag:cFjrjuXHy+Rb2QhzzbQqbg==,type:str]
    AUTHENTIK_BOOTSTRAP_PASSWORD: ENC[AES256_GCM,data:F4ZkQg6Is+C8cL03LC/L6eI=,iv:b0Ak2d0UsTVvXV+J7T7B6WXTYrC2OCGZ+DREePQEvDc=,tag:A/YIXEZFsdY4V4Bk2dH20w==,type:str]
    #ENC[AES256_GCM,data:3uawXc4kDTEm,iv:/opnHpRMxQIvp4G54lhuKGo4svfLuuj2O17RRrRWNoQ=,tag:njoOq1+iZBwzdeU6+G9iQw==,type:comment]
    AUTHENTIK_POSTGRESQL__HOST: ENC[AES256_GCM,data:yRMrAUuJ3FkV1t0efTPX,iv:lf9SpF1ToJdgtnPOsjWfU5+QTactavlJQudkVSkNGbA=,tag:mN+dMUTvGhHbX18ij5Z8rg==,type:str]
    AUTHENTIK_POSTGRESQL__USER: ENC[AES256_GCM,data:MAKOayMRejd9,iv:qOU78QXXJqlsv3c10SX0vZaqdCCDlExwRqf/2NYRJCc=,tag:rV8dGqAgU8+7L7ghrtbBBw==,type:str]
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:j6gLSY8Sc4/9RBBLEt+6xFb+s9ccGnWfq13aBG1culS+M0Fcu9zXBFLn2ys=,iv:0p9rNwbNkKtQTOH+O9rTOZ2vn9QVUJ+VUOh633W/8wk=,tag:T+328XpS/oPQbIZEIo4YIw==,type:str]
    AUTHENTIK_POSTGRESQL__NAME: ENC[AES256_GCM,data:gptj47rrqLsf,iv:siaelI5mhomrYv7z7OUgUHA8ltaCGMGOsLCKWFmEl+s=,tag:4EKbT4C4CSw/qRgm0tiedQ==,type:str]
    #ENC[AES256_GCM,data:sQSWsr4=,iv:5nMPs4H4xcyHXld3guzcjj/VFeXy5l99CyZBssZhXL4=,tag:n6dWfTxLdpaTPKbaNOgkzg==,type:comment]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:ifStCQYHNCgz,iv:R3G62DXW0EOOkdavo1m5Rg4ow/O9yhvPzKAgJ9PWh/w=,tag:HoDWFrNWdNFS7IPuP1R09w==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:f/zxaB/LbffM,iv:LFCVTSLq7PIvyyTAEcigXc8o5YgWsFXHacMV7W5BRa4=,tag:bZ0MciipY9UE79Hr5KQKvA==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:/HFl6/R+d0zKX+rggh3HVbTrDiCPSe9Xe3v9ip4/nHyhL2RmSfx3vDN3sf4=,iv:W02xUBWKtqSawRkcY1+S94BxZzfwbWrfO9aU2GIl5/w=,tag:KulXBA0dIBsyN7BlWejSHA==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:bt8YUqph6RQIP7xUKjsl,iv:hUfi3csTLu3I1BuKN/ZkE/UWcXj389VdwGhdZUn1lbY=,tag:App6umb5uzgtCU16JKfO1w==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:p004/0VtN2YNfDM+zOCx42/g0nsFe4HKxQWSczMwlS1eFtflerJxOQh3g7g=,iv:2AqseS7kbj6T/ITl1mvMWaV1DZXFoFZPbUCkd3cmy8k=,tag:s+Uy9W0hEEd7lLUp5nRObg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpR0hQQ044dkFtNXRtaHd1
            QndGRzBFYytJdTV3ZG9LMVI1Q1dZL2lNTFdzCjZIMEtWMnEwdjBPODUwV1d6M0Fx
            SDhKa1p6dUduVHdlLzdQc3lLUGZiSHMKLS0tIDdmYm9xM2hYdDI4dDV0cGY2OTNH
            NXF5YVpGYlVieDZkbkFMWU5pZTF5djgKrxhlX+nW3y5lfMWEkG8V/qiwtlOAq5T0
            C/Lb/XK9gHPvFw5j8ZPDRJiV352rLVVNn0sAycs1rb9WZJupI47YSg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xlls984taykl6jyq0f965lyx66qj6e4cg4wqwrfav258c5gpr44qkwuv3w
    encrypted_regex: ^(data|stringData|((?i).*(API_KEY|TOKEN|SECRET|USER|EMAIL|ZONES|DNSNAMES|CLIENTIP).*))$
    lastmodified: "2026-05-28T21:06:08Z"
    mac: ENC[AES256_GCM,data:dCieADiw5pLWyrd/O5q/ESYc2uYQcQ/s9zvWtnu7s6sP4AdvhWYenz+kORzKl/QCe8LTLJfFX5G8OtQB+rytOG/Zcog4CszT2gEogU61TyBGAEiBGOE/ZSpAENKRSOAdmjEVhUu+kvV95sbQAvOxHWozfMBReYkFUwxuTfc4Jmo=,iv:o2Gel/uOnfV8C7bAMzSCMbS5Jj6M3ij9U7vpCAfXp4I=,tag:lSnRR/86bxg0miIEAxsqzg==,type:str]
    version: 3.13.1
