---
services:
  shepherd:
    image: ghcr.io/kondanta/shepherd:2026.8.1
    restart: unless-stopped
    container_name: "shepherd"
    ports:
      - "11250:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${ROOT_DIR}:${ROOT_DIR}
    env_file:
      - .env
