---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlertmanagerConfig
metadata:
  name: chaski
spec:
  route:
    receiver: chaski-discord
    group_by:
      - alertname
      - namespace
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
    routes:
      - receiver: null
        matchers:
          - name: alertname
            value: InfoInhibitor|Watchdog
            matchType: =~
  receivers:
    - name: chaski-discord
      webhook_configs:
        - url: http://chaski.selfhosted.svc.cluster.local:8080/hooks/alertmanager
          send_resolved: true
    - name: "null"
