---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: vm # VictoriaMetricsK8sStack
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.58.2
  url: oci://ghcr.io/victoriametrics/helm-charts/victoria-metrics-k8s-stack
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vm #VictoriaMetrics
spec:
  interval: 15m
  chartRef:
    kind: OCIRepository
    name: vm
  values:
    victoria-metrics-operator:
      createCRD: true
      operator:
        disable_prometheus_converter: false
    # Disable components we don't need yet to save resources
    vmalert:
      enabled: false
    vmalertmanager:
      enabled: false
    vmsingle:
      extraArgs:
        search.enableLabelAPI: "true"

      storage:
        volumeClaimTemplate:
          spec:
            accessModes: ["ReadWriteOnce"]
            storageClassName: longhorn
            resources:
              requests:
                storage: 10Gi

    vmagent:
      enabled: true
      spec:
        serviceMonitorNamespaceSelector: {}
        podMonitorNamespaceSelector: {}
        serviceMonitorSelector: {}
        podMonitorSelector: {}
        extraScrapeConfigs:
          - job_name: kubernetes-nodes
            kubernetes_sd_configs:
              - role: kubernetes-nodes
            scheme: https
            tls_config:
              insecure_skip_verify: true
            bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
            relabel_configs:
              - action: labelmap
                regex: __meta_kubernetes_node_label_(.+)
              - target_label: __address__
                replacement: kubernetes.default.svc:443
              - source_labels: [__meta_kubernetes_node_name]
                regex: (.+)
                target_label: __metrics_path__
                replacement: /api/v1/nodes/${1}/proxy/metrics
          - job_name: kubernetes-cadvisor
            kubernetes_sd_configs:
              - role: node
            scheme: https
            tls_config:
              insecure_skip_verify: true
            bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
            relabel_configs:
              - action: labelmap
                regex: __meta_kubernetes_node_label_(.+)
              - target_label: __address__
                replacement: kubernetes.default.svc:443
              - source_labels: [__meta_kubernetes_node_name]
                regex: (.+)
                target_label: __metrics_path__
                replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor
          - job_name: "kubernetes-event-exporter"
            static_configs:
              - targets: ["event-exporter.your-namespace.svc:80"]
          - job_name: kubernetes-pods
            kubernetes_sd_configs:
              - role: pod
            relabel_configs:
              - source_labels:
                  [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
                action: keep
                regex: true
              - source_labels:
                  [__meta_kubernetes_pod_annotation_prometheus_io_path]
                action: replace
                target_label: __metrics_path__
                regex: (.+)
              - source_labels:
                  [__meta_kubernetes_pod_annotation_prometheus_io_port]
                action: replace
                target_label: __address__
                regex: (.+)
                replacement: $1

    kube-state-metrics:
      enabled: false # TODO: This doesn't support customResourceState. I'll deploy it separately.
      vmScrape:
        enabled: true
    grafana:
      enabled: false

    kubeEtcd:
      enabled: false

    defaultDashboards:
      enabled: true
      labels:
        key: value
      annotations:
        key: value
