all:
  vars:
    control_plane_entpoint: 192.168.1.100
    load_balancer_ip_pool: 192.168.1.225/29
metal:
  instances:
    control_planes:
      cplane1:
        {
          host: 192.168.1.110,
          mac: "E8:FF:1E:D4:75:D5",
          disk: nvme0n1,
          network: eth0,
        }
    workers:
      worker1:
        {
          host: 192.168.1.111,
          mac: "E8:FF:1E:D4:7C:1F",
          disk: nvme0n1,
          network: eth0,
        }
      worker2:
        {
          host: 192.168.1.112,
          mac: "E8:FF:1E:D4:76:1B",
          disk: nvme0n1,
          network: eth0,
        }
