---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
spec:
  interval: 1h
  chart:
    spec:
      chart: authentik
      version: 2025.12.3
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
      interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    global:
      image:
        repository: ghcr.io/goauthentik/server
        tag: 2025.12.3
      podAnnotations:
        reloader.stakater.com/auto: "true"
      deploymentStrategy:
        type: RollingUpdate
      env:
        - name: "CHECK"
          value: "1"
      envFrom:
        - secretRef:
            name: "{{ .Release.Name }}-secret"
    worker:
      replicas: 1
    server:
      replicas: 1
      initContainers:
        - name: init-db
          image: ghcr.io/onedr0p/postgres-init:17.4@sha256:43dd04e91e861cf912378bad987afa168fa4f13d05528304907ad0aa351195d6
          envFrom:
            - secretRef:
                name: "{{ .Release.Name }}-secret"
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
    route:
      app:
        hostnames:
          - sso.taylan.dev
        parentRefs:
          - name: internal
            namespace: network
            sectionName: https
          - name: external
            namespace: network
            sectionName: https

    prometheus:
      rules:
        enabled: true
    redis:
      enabled: false
