---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
spec:
  interval: 1h
  chart:
    spec:
      chart: authentik
      version: 2025.12.3
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
      interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    global:
      securityClassName: security-critical
      podAnnotations:
        reloader.stakater.com/auto: "true"
      deploymentStrategy:
        type: RollingUpdate
      env:
        - name: "CHECK"
          value: "1"
      envFrom:
        - secretRef:
            name: &secret authentik-secret
    server:
      replicas: 1
      env:
        # Authentik native OTEL support (don't use auto-instrumentation - it conflicts)
        - name: OTEL_SERVICE_NAME
          value: "authentik"
        - name: AUTHENTIK_TRACING__ENABLED
          value: "true"
        - name: AUTHENTIK_TRACING__EXPORTER
          value: "otlp"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://tempo.observability.svc.cluster.local:4318"
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: "http/protobuf"
        - name: OTEL_TRACES_EXPORTER
          value: "otlp"
        # Propagators for trace context extraction from incoming requests
        - name: OTEL_PROPAGATORS
          value: "tracecontext,baggage"
        # Sampler configuration - always continue parent traces
        - name: OTEL_TRACES_SAMPLER
          value: "parentbased_always_on"
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "service.name=authentik,service.namespace=selfhosted,app.type=identity-provider"
      initContainers:
        - name: init-db
          image: ghcr.io/home-operations/postgres-init:18.1
          envFrom:
            - secretRef:
                name: *secret

      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
    worker:
      replicas: 1
      env:
        # Authentik native OTEL support (don't use auto-instrumentation - it conflicts)
        - name: OTEL_SERVICE_NAME
          value: "authentik-worker"
        - name: AUTHENTIK_TRACING__ENABLED
          value: "true"
        - name: AUTHENTIK_TRACING__EXPORTER
          value: "otlp"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://tempo.observability.svc.cluster.local:4318"
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: "http/protobuf"
        - name: OTEL_TRACES_EXPORTER
          value: "otlp"
        # Propagators for trace context extraction from incoming requests
        - name: OTEL_PROPAGATORS
          value: "tracecontext,baggage"
        # Sampler configuration - always continue parent traces
        - name: OTEL_TRACES_SAMPLER
          value: "parentbased_always_on"
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "service.name=authentik-worker,service.namespace=selfhosted,app.type=identity-provider,component=worker"
    route:
      main:
        enabled: true
        hostnames:
          - sso.taylan.dev
        parentRefs:
          - name: internal
            namespace: network
            sectionName: https
          - name: external
            namespace: network
            sectionName: https
        https: true

    prometheus:
      rules:
        enabled: true
    redis:
      enabled: false
