apiVersion: v1
kind: Secret
metadata:
    name: authentik-secret
stringData:
    POSTGRESQL__NAME: ENC[AES256_GCM,data:t6P4hs3mALtH,iv:4j8QxxDTNlZFJth72y62qqvo5cTP1Kea+1PNofB/4iQ=,tag:XcrQaO8466tDrBm9WtYmEg==,type:str]
    POSTGRESQL__HOST: ENC[AES256_GCM,data:aJBDS9HIACKyiNzAvi/T1rV0NjI2wYhIcB5I4XOJoGZwDU114W4=,iv:5zUDjEpCsch6INLgc2bKIl7HMyvzf0LnLpHtsxcjk30=,tag:A33pRBJ8lzmnidy8qd+LlQ==,type:str]
    POSTGRESQL__USER: ENC[AES256_GCM,data:IqRlYgiP,iv:wgUzPfWCLXcVFenQ3KEYzx35AY6BVK8c09IgMHLzT8M=,tag:sjCFmawmUd8UHUNiL/NhoQ==,type:str]
    POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:ab9CGhLQCG032YhDBWw=,iv:HtlQHTKx4jAr9i71q8p4GnKPPOo6E8m1hFn3tUSor6Q=,tag:zKBEc3KLaGXteXc8NsIbjQ==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:HwPm2WlXo7Mj,iv:UAA+38M/XID7pC02LozoHPx5L7rNrOJ/DZ/vyIkXXpo=,tag:6Zfv/TCYeULQtNz+ae2VSQ==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:0/u1J2EHiJK9+eJZbE3W9+QrDkLjusNFLdQ4DUdBigtBJZpJAlg=,iv:D+9vRcwcpKjmNfH5kG/KM/zicUZLf4jb9qzM/8xuEK4=,tag:QH7WWrB/4frGWbwb9skJ/w==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:8iTHam/2,iv:dlr0WYQczMqKCuXer46koF0ZrEBwlqZX2E/RuK2xYw0=,tag:bL2YlLt7jWLcaIq4Vili6w==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:XDjLz98UOy5W6wiA/XI=,iv:Hda6n+3BKsetfmwZXtcHj1mjFysY16YFmNVA3zRz1os=,tag:RSODn+1zzSaNUv0EeaqUDQ==,type:str]
    INIT_PASTGRES_SUPER_PASS: ENC[AES256_GCM,data:HDZQ8E6DmtRYEqg5/4Fwgb+3NA==,iv:ZZPJzCXau4IfvSD39/0DI6U0ax+IMPST1ZnaUbowh6o=,tag:HzA4ATjkV+mdZpegrwWUwQ==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:yS8sClG6pIUQ/oCYAaxQiBN8uQR9kynPEh4gm7Bbp78B+M5KSwiAVd6f4ws=,iv:Y13x5jpVhM4R29u20Hn0MoIXzbSQFD0lBRJyIqCmlE0=,tag:QoKnsa9fO5fBtEdHnM1hag==,type:str]
sops:
    age:
        - recipient: age1xlls984taykl6jyq0f965lyx66qj6e4cg4wqwrfav258c5gpr44qkwuv3w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1RVhySkQvbldLTFRXNUlw
            YlN3NmNLcm5vYUJOb1ZLc0QzR0xVcERiMFQwCmdpM2piaDJ0cXZCb21FQU9CYk1Q
            T0l2Ym5XL2p0UFNhZjFRY2MvcFpDS0EKLS0tIERiMW4zVmtJdmRPc1NsVkttd1dv
            bi80NVAxTEV0STIva2hkVTF4V2NnclkKOgwNfc3GUx/PnK0Zu/X0sllVWu6TKEpJ
            U9WmhggTju3qKIqjHJ2yPagRPjwpfjxJdfuoPkLPZY0fiYiLKFtvhg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-05T21:19:39Z"
    mac: ENC[AES256_GCM,data:lEKulSylBJJDZc9F3n6gvAFSAWFqgxI/Qyj0uG/9zW8MttWHVljEa+l3asoNIXMNzpq/b79HM5PwaCiVZxE+ZRSwR8lzYJNWQKvLtFD090y7sPK9PqL07UqZerhJij95HKZQFhgrGlu8OXaH2XFNDP7taGAS98485iyOT9BqGgY=,iv:r2irMbudSwNVxFw64TR/VZwqmHOn2Wjqx7onxjNm8jc=,tag:bY6HffHn7LvV7AgyH/Psvw==,type:str]
    encrypted_regex: ^(data|stringData|((?i).*(API_KEY|TOKEN|SECRET|USER|EMAIL|ZONES|DNSNAMES|CLIENTIP).*))$
    version: 3.11.0
