# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/core/secret_v1.json
apiVersion: v1
kind: Secret
metadata:
    name: adguard-dns-secret
stringData:
    ADGUARD_URL: ENC[AES256_GCM,data:zZxzyKd+5ofRH1fA9mqsFVLd,iv:woveMobK2DL2iPSBd/baaurPT0qad4tpQNxJT9Rig9o=,tag:rAOYyMrdywBIryUCoE+jEA==,type:str]
    ADGUARD_USER: ENC[AES256_GCM,data:WdpdkuQ=,iv:ksPqi4OWUivY2wMpQNMrxEOQ954+pMkt4MYGbhT2tZU=,tag:FWpCCSNs7oMe8yorFkry8w==,type:str]
    ADGUARD_PASSWORD: ENC[AES256_GCM,data:5udgvjwe8B+8XMko5hA=,iv:vnrZJn0DpoY8puCFAqGZBShXtqcaDu4UAUs9Xktnvpg=,tag:2BHYBRUuYXVEWcXVlpN+og==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCSXBjQStqNDJubS91UW1P
            YkM5L00wTTVZTFl3NTZ3UWNUZVNGR002b3hrCm1vQ0RCU2ZVYkF5d0JadUJRdGN3
            eGNxNElqRWRKWjVSV2M0ZUY4S3JJUGcKLS0tIFlFMzFFUk5XYndkMjlYeW50V2Nm
            SVNZWGwwNUxyZHBuRUJjY09nTGNwRHMK0TPKHNBfVXMM3EMgl5zx/A/rLSo1pgmH
            UKBikhC/77GMLIxmSFMriZz3TzU+JZyozAfT1gI2460AsqfeuSKp5w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xlls984taykl6jyq0f965lyx66qj6e4cg4wqwrfav258c5gpr44qkwuv3w
    encrypted_regex: ^(data|stringData|((?i).*(API_KEY|TOKEN|SECRET|USER|EMAIL|ZONES|DNSNAMES|CLIENTIP).*))$
    lastmodified: "2026-06-28T21:16:59Z"
    mac: ENC[AES256_GCM,data:Ju6NW2eszCuikSjxWeDMst2l8EyRJGoI0H84ZxpYEnuhYr8+jqtFzB+NisXk+ptAh3AGJYy07BoTIffKZ33LNij2QS/KDl8sf0eXABBKg8WSq6h/CIvo4KO3syb5RDki3rfm8+O7PtpWDNCyuaJQtWeIm5QU25+d904D+R2ze3k=,iv:R4uw6xzW8oHee3/lFjVRYc6ZbgvuvapiR2rzK7XOtl8=,tag:Qjs6AgzS/h1vaEATmCm2Sw==,type:str]
    version: 3.13.1
