---
cgroup:
  autoMount:
    enabled: false
  hostRoot: /sys/fs/cgroup
devices: enp1s0
enableRuntimeDeviceDetection: true
endpointRoutes:
  enabled: true
envoy:
  enabled: true
  rollOutPods: true
gatewayAPI:
  enabled: true
  enableAlpn: true
hubble:
  enabled: true
ipam:
  mode: "kubernetes"
k8sServiceHost: localhost
k8sServicePort: 7445
kubeProxyReplacement: true
l2announcements:
  enabled: true
loadBalancer:
  algorithm: maglev
  mode: dsr
operator:
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
  replicas: 1
  rollOutPods: true
prometheus:
  enabled: true
  serviceMonitor:
    enabled: true
    trustCRDsExist: true
rollOutCiliumPods: true
routingMode: tunnel
securityContext:
  capabilities:
    ciliumAgent:
      - CHOWN
      - KILL
      - NET_ADMIN
      - NET_RAW
      - IPC_LOCK
      - SYS_ADMIN
      - SYS_RESOURCE
      - PERFMON
      - BPF
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    cleanCiliumState:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE
tunnelProtocol: vxlan
