---
crds:
  enabled: true
dns01RecursiveNameservers: https://1.1.1.1:443/dns-query,https://1.0.0.1:443/dns-query
dns01RecursiveNameserversOnly: true
prometheus:
  enabled: false
  servicemonitor:
    enabled: false # enable ServiceMonitor for Prometheus after installing the Prometheus
replicaCount: 1
resources:
  requests:
    cpu: 50m
    memory: 96Mi
  limits:
    cpu: 50m
    memory: 96Mi
cainjector:
  resources:
    requests:
      cpu: 50m
      memory: 192Mi
    limits:
      cpu: 50m
      memory: 192Mi
webhook:
  resources:
    requests:
      cpu: 25m
      memory: 48Mi
    limits:
      cpu: 25m
      memory: 48Mi
