---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - metallb.yaml
  - cilium.yaml
  - jetstack.yaml
  - emberstack.yaml
  - namecheap-webhook.yaml
  - longhorn.yaml
