---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMStaticScrape
metadata:
  name: adguard
  namespace: observability
spec:
  targetEndpoints:
    - targets:
        - "10.1.20.52:9100"
      labels:
        job: node-exporter
        instance: adguard-host
      interval: 30s
      path: /metrics
    - targets:
        - "10.1.20.52:9618"
      labels:
        job: adguard
        instance: adguard-host
      interval: 30s
      path: /metrics
