---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMStaticScrape
metadata:
  name: qnap
  namespace: observability
spec:
  targetEndpoints:
    - targets: ["10.1.20.100:9100"]
      labels:
        job: node-exporter
        instance: qnap-nas
      interval: 30s
      path: /metrics
    - targets: ["10.1.20.100:9633"]
      labels:
        job: smartctl
        instance: qnap-nas
      interval: 10m
      path: /metrics
