apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homelab-wildcard-cert
  namespace: cert-manager
spec:
  secretName: homelab-wildcard-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "${SECRET_DOMAIN}"
