apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
    name: homelab-wildcard-cert
    namespace: cert-manager
spec:
    secretName: ENC[AES256_GCM,data:QErz40Rk/V3SUv/5/RhOysBit+o=,iv:t6N3XjSzenNntd8oy3xutOztY3ucpSXovSRl0ghYkX0=,tag:SqPBZ6B6lSzOcmyIGytHRw==,type:str]
    issuerRef:
        name: letsencrypt-prod
        kind: ClusterIssuer
    dnsNames:
        - ENC[AES256_GCM,data:Jva/KFFytBpJoR52LTvg9rP+avpcPezYn5Q=,iv:AREnKUnHKEGhJtXCP8rmSScEZYrfATOXTisGWAN3nSQ=,tag:r5OI5H6FtSQiK2AyK8l5Aw==,type:str]
sops:
    age:
        - recipient: age1xlls984taykl6jyq0f965lyx66qj6e4cg4wqwrfav258c5gpr44qkwuv3w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiNjljQzhHM3ZIcVVXejRr
            Sy91UDFzS0M1TUJYbWVGcGQ1eHBUOHlDYm1BCm10dmdGTkREcjd4MVZYM2dxUm9Y
            L3c1ZW9LYVQxajhja21WNkMrY3NxU2sKLS0tIERRamlvWlJzZ0hiTW5qWEx5aUpL
            K0ZJNXp1R0hUa25HYnJIQXpXYWZ6L3cKh5Mdz70CkXxw1bjJOHajeVgDrcRf6Jst
            yx1dS0kc82xIf79J5AWyo5SG+DJZxkVeIQ3x/27Ic2yfIVPgRZOg1A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-12T13:55:05Z"
    mac: ENC[AES256_GCM,data:FYjNh44xi4JFAOCPrGK8kPmtd0Ll8XD4n6MrqDKUtezYhjG6sYlrP2NDsP1W51/RQ4IhmiKrV1OKtYRDMUoXvRj2Vuj4kTKw5MCkO2EmS7Gi6JgFWvTJ1aRkWbpJslHRJbTNnw+7WFnLnOTQ0JyscRSa6IRqs/n2AeQKGhXRlCk=,iv:xuooHvmAdbn0gcZl6eseMZjpGCwHYGXDIaH28QlbqOs=,tag:11TwWAEBXWV5I1alD3o1+g==,type:str]
    encrypted_regex: ^(data|stringData|((?i).*(API_KEY|TOKEN|SECRET|USER|EMAIL|ZONES|DNSNAMES|CLIENTIP).*))$
    version: 3.10.2
