apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: letsencrypt-dns-namecheap
spec:
    acme:
        email: ENC[AES256_GCM,data:/yGqQbYIAwL8DDWORvKJWo1LTm4=,iv:o2r71djVXB9HLe1EcjaVmhGw7H3swSvrxg8mzF3Grzo=,tag:TufAQcJgFnuoYXHV6OwvKw==,type:str]
        server: https://acme-v02.api.letsencrypt.org/directory
        privateKeySecretRef:
            name: ENC[AES256_GCM,data:a5Ymt/084yXN3Vdf+LshnX4eWg==,iv:akpzBk0hdbUMn86Z3sFRiZ6ySX4mY05m32bzvCigCyA=,tag:Ed2ipBd1uixrq578fXvVAg==,type:str]
        solvers:
            - dns01:
                webhook:
                    groupName: acme.namecheap.webhook
                    solverName: namecheap
                    config:
                        apiUser: kondanta
                        apiKeySecretRef:
                            name: ENC[AES256_GCM,data:a916s2ibxn+twCTF4uSHn34=,iv:b5BBbYHVBDVe+Nb+BK9zIa01YKj20OjXVTzwxKDHaNo=,tag:+oaE4QwsCZpqgxR+Q2i0HA==,type:str]
                            key: ENC[AES256_GCM,data:6OIFqMsaMw==,iv:Ow4CFb3OuX6An1a0dzJUw0KbREkXf+YnhLvX66peUUU=,tag:957nqqYi784VR2hF3AYIVA==,type:str]
                        clientIp: 81.191.122.238
sops:
    age:
        - recipient: age1xlls984taykl6jyq0f965lyx66qj6e4cg4wqwrfav258c5gpr44qkwuv3w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiNjFwWEc1czdDWXV4c1hO
            TXhIMUc1bUYyZ3E4U21mT3BLUHpudmNKSDFFCnIzUkdsc2lwY1VaZlZKL3d3dmN2
            KzJuSGgxeVdwQ1V6bnZPZEs4Q1R2VzgKLS0tIHRESFRTRnZTUEw2K2c3ZWJBbktZ
            emUvWUNkejlXQWRNbHNUTTVWT3VYM1EKrydiFtRBa+5AgLeDBOYPnd93Zr+EQJox
            UEsTEXhtbppF4s+l+ubHXxJWkyI3wW/8Zy3IBLsZlwD3xHGjf0Wuxg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-12T04:07:54Z"
    mac: ENC[AES256_GCM,data:IIkgENp3OW23ZtXeDMqNCw5oxbgexF63S6WngxXGmBrYrthuj6MHQ1pG5JEes7tlEDtydHGHmgkhxB1kA4YbiE15V9IeiLN4hwL4q82AxEjjgpygqsMEApFy75HouPLAi2uiGRe3LOhaXLK0OKKwPQrfSjpx2hrfqMuo9SZkboI=,iv:tkjLTnuKw526AwJ6+cG/bRhokVY1nxmaertBHBDIeCo=,tag:N8S1cxQVCcn9njZZ5G2x2Q==,type:str]
    encrypted_regex: ^(data|stringData|((?i).*(API_KEY|TOKEN|SECRET|USERNAME|EMAIL|ZONES).*))$
    version: 3.10.2
