apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager-webhook-namecheap
  namespace: cert-manager
spec:
  interval: 30m
  chart:
    spec:
      chart: cert-manager-webhook-namecheap
      sourceRef:
        kind: HelmRepository
        name: cert-manager-webhook-namecheap
        namespace: flux-system
  values:
    groupName: acme.namecheap.webhook
  postRenderers:
    - kustomize:
        patches:
          - patch: |
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: cert-manager-webhook-namecheap
              spec:
                template:
                  spec:
                    securityContext:
                      runAsNonRoot: true
                      seccompProfile:
                        type: RuntimeDefault
                    containers:
                      - name: cert-manager-webhook-namecheap
                        securityContext:
                          allowPrivilegeEscalation: false
                          capabilities:
                            drop:
                              - ALL
