apiVersion: v1
kind: Secret
metadata:
    name: namecheap-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:l0LW0sZy6N1OXyTUT6kzqE712D0N0GLcVkBxVHEzQKs=,iv:f3u7jRXQDonKzct6ySES9sD5YUeqcMTp/qFJyeAy4M8=,tag:0vftwdLthgm02EWOEAm48g==,type:str]
sops:
    age:
        - recipient: age1xlls984taykl6jyq0f965lyx66qj6e4cg4wqwrfav258c5gpr44qkwuv3w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxcnRxc2Y3bzU2cHhXeG9v
            YXY3SSs1UXNoQ2J6SDNQeTdpZ0VpbDdVQmlrCndFN2V0aGVmeXZ1N3p4OVFhY3pj
            MFlrdVhydmRWQ2tzQ01YQW16OHc0UjQKLS0tIE13Qkw3NDRXTkk1N1U3Y0E4Y3Nm
            cVFjREtwNWJ0TmFJM2JmMXpheEVnK1UKk/6WUF0BA32gnPFAdWuS/yBCYP1LYG5r
            UuSembtlQLTROqh7pVoYRydSNmal/MDvrHiBslT/M7WNf0tnDZQyCw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-12T13:55:44Z"
    mac: ENC[AES256_GCM,data:H8eYV4Z/sxm+Pj/UUH+CQmijnzWWa3OdcZ7RGI/okfPGpbXK4kdajEveikRZNH8HCN9Wj03Wx9sVyArOhHluqD0neNovpR6gmcJezWNlwjrkqTokf9eib6/FAYtf128upRr6/VMf4sBQxfuI64Kn55xcecoWJdlUqStbRSog9C8=,iv:tY34RoafJ4lUkbFvE108auCVFksCtrJwpnrPK1/EEE0=,tag:7qNmk1h6qfh7iYpq0lLsyA==,type:str]
    encrypted_regex: ^(data|stringData|((?i).*(API_KEY|TOKEN|SECRET|USER|EMAIL|ZONES|DNSNAMES|CLIENTIP).*))$
    version: 3.10.2
