apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager-webhook-namecheap
  namespace: cert-manager
spec:
  interval: 30m
  chart:
    spec:
      chart: cert-manager-webhook-namecheap
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: cert-manager
  values:
    groupName: acme.namecheap.webhook
