apiVersion: v1
kind: Secret
metadata:
    name: namecheap-api-key
    namespace: cert-manager
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: external-dns
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: external-dns
stringData:
    api-key: ENC[AES256_GCM,data:5mCDnhTMCiZ1YpzLQmkeiujuFOq7wBdgXoDkvnC7gkA=,iv:0ZKbGo8zfJInjhOWBi06jC9Tmo2TLDkDDzBDDrE3Mi8=,tag:6q3TyK7bsuzeDaBvSENEEg==,type:str]
    api-user: ENC[AES256_GCM,data:VGJg39Q8iSg=,iv:jmF3DrLmOUNZSpRHcu0kZSZqw/PuDkY2goJWpGnj+pc=,tag:ogaigBfmY8xgBeFnLz+bTw==,type:str]
sops:
    age:
        - recipient: age1xlls984taykl6jyq0f965lyx66qj6e4cg4wqwrfav258c5gpr44qkwuv3w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5eW5LYkZwdFh3Z2FUTjl2
            UGdEdGxTWjNTSTVYRGlBdkloeldLZHZROGhrCnUxY2IzOG5ndmx6b1hZM3RsNHFF
            aFp2T09LbnFHcUtza1h4ZHlEQUk4NTQKLS0tIHhOSTB2bndsS1ZkT3ArenVmbHhL
            R3FMWW9JUWVid3l4ZENjN2kxWXNXY0kKzAGp37kVCN1XeG8b7uYQhGuZ7ZPiY1cU
            uhOJPKoJP00jRWnetrNPp3fx+w7TSUoPNcDUZI6bu5wFKZ2JSorHew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-13T23:13:02Z"
    mac: ENC[AES256_GCM,data:KUZLeqIzZUD+zc1cHkocbrGOequU2JM1x1Zd35ncLQHBtTasNgxABxCsxfpcmK7yD1WmvqZKgXYg7JOK3iGG3tgWFDiTG+XQz1vuVWu13AEQu3+/RNFUQznVooAXr/dJNx9KOeL3jPKF4KE1od+BN57qt8mkyjpA8QOAiEfj9sc=,iv:2KwyP8T92XFv9GXoEr/Sc+xnbrp1KT3rLy8OKeRQjI8=,tag:YryiMxK0Iuj/6B6RzPlRCw==,type:str]
    encrypted_regex: ^(data|stringData|((?i).*(API_KEY|TOKEN|SECRET|USER|EMAIL|ZONES|DNSNAMES|CLIENTIP).*))$
    version: 3.10.2
