apiVersion: v1
kind: Secret
metadata:
    name: namecheap-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:BcrfkJCX3CGavHX2VRf1BU+77vuGk+RCELLD2aYI9lo=,iv:JO5XfZqcMaKfywf0A7eTm5gxEh0VQE6aUupffa5u9e8=,tag:mGsUpLVNgXMTV7Qlex5i8w==,type:str]
    api-user: ENC[AES256_GCM,data:oedc0k8yI5k=,iv:FRkVUIRNuSQPWP98mgZ3YhzepHml8e9dA85MqwzSJT8=,tag:6K6MPvWiWa+I9U9W2OMDVA==,type:str]
sops:
    age:
        - recipient: age1xlls984taykl6jyq0f965lyx66qj6e4cg4wqwrfav258c5gpr44qkwuv3w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzK3lSY1pyRjBPbkV5am1F
            ZWtLakdnOVU3eGtWUnJzc04zUWJ6SzNINGc0Cmo0bUZUL1VrampTSTVjSVpEV0ta
            bEV0dzhLWDJUUTQ2OFNTT3l1OTh2MG8KLS0tIHB5UFlKRWx0K2tkWklVVUhGK1VU
            S3lzNnFlc2RzWVAyNlEyM0FVSzBKMlUKcKjY4y5rumBbVHUG1MXdESsdIfJQiLgS
            GCBf5iLA3oNjdxlRrti5S9jF2VKJ3LuXBOJirWGy2xo/IL1dCydmvw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-12T15:20:30Z"
    mac: ENC[AES256_GCM,data:+2KaV5gChm2GpWKKfTsc+xD6C/RxDSTps+HPPp76SKEwHXh40zBT004qfIdmjdEatHR7j3+DyrjyCjbPPR9ohiG8g800p1H8SHQkv74exGkE6DLuopFiQjzxCQiKF2uLbdGu/Vu0JDrX/Ab3KHP02LCs9avmjjV3/99PYrbqSaw=,iv:ztBGIGdHhWdWcZvZUft55i/20tH+DqMcHfi7YQQwceA=,tag:tfyWAgyl6ZiFnp2NpSaA/A==,type:str]
    encrypted_regex: ^(data|stringData|((?i).*(API_KEY|TOKEN|SECRET|USER|EMAIL|ZONES|DNSNAMES|CLIENTIP).*))$
    version: 3.10.2
