---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager-webhook-namecheap
  namespace: cert-manager
spec:
  chart:
    spec:
      chart: cert-manager-webhook-namecheap
      sourceRef:
        kind: HelmRepository
        name: cert-manager-webhook-namecheap
        namespace: flux-system
  interval: 30m
  values:
    groupName: acme.namecheap.webhook
    postRenderers:
      - kustomize:
          patches:
            - patch: |
                apiVersion: apps/v1
                kind: Deployment
                metadata:
                  name: cert-manager-webhook-namecheap
                spec:
                  template:
                    spec:
                      securityContext:
                        runAsNonRoot: false # The container only runs as root
                        seccompProfile:
                          type: RuntimeDefault
                      containers:
                        - name: cert-manager-webhook-namecheap
                          securityContext:
                            allowPrivilegeEscalation: false
                            capabilities:
                              drop:
                                - ALL
