apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 15m
  chart:
    spec:
      chart: longhorn
      version: "1.8.2"
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  values:
    persistence:
      defaultClass: true
    ingress:
      enabled: true
      ingressClassName: cilium # This tells Longhorn to use the Gateway API
      host: longhorn.homelab.taylandogan.info
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-dns-namecheap"
