---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: external-snapshotter-crds
  namespace: flux-system
spec:
  interval: 12h0
  ref:
    tag: 8.3.0
  url: https://github.com/kubernetes-csi/external-snapshotter
