---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: external-snapshotter-crds
  namespace: flux-system
spec:
  interval: 12h
  ref:
    branch: master
  url: https://github.com/kubernetes-csi/external-snapshotter
