apiVersion: v1
kind: Secret
metadata:
    name: cloudnative-pg-secret
stringData:
    username: ENC[AES256_GCM,data:Pwsy+3INa/Q=,iv:43QzwRhFxuObpxtCGfGBGDvesHW3yHzme5NiktXKuWs=,tag:gJWI8wy5v+skxN+NcUepsg==,type:str]
    password: ENC[AES256_GCM,data:S/B4H7w56IzkyexnRj6yfoXLDlpHI5m/5faGhi8jXu8BromgrMj7dJgM9R0=,iv:DesoscipUZavdRD91bRwiitwbh27HzPm+5WUgzNdfsQ=,tag:SufHNrrdXiUS5ikHjF9jrQ==,type:str]
    POSTGRES_SUPER_USER: ENC[AES256_GCM,data:ka0W4bidI2A=,iv:GCCBRNB9DwjRQ5BGKxi+1sCKGs+Z4PHGQT+HEyc5gzQ=,tag:i+/kCXfbClCOnyI6yo2AGw==,type:str]
    POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:VxyjwzXDa2TBpcUgq2YFKuutOl3kuaHU0K3Z9NkAkI1oBlQV9da9YKESRNQ=,iv:uzXxP6Je+P4dPfeYLdeT5id3J3Hg+mGsRHnUB9qcKR4=,tag:I8l64h0xzB1zqCqb27KvOQ==,type:str]
sops:
    age:
        - recipient: age1xlls984taykl6jyq0f965lyx66qj6e4cg4wqwrfav258c5gpr44qkwuv3w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBndDcvZUV1OE1MVmNpN2Zi
            cUY2VXlmZ1d6K1dTVnpUU3A2S3lROXdEaG04CkFRL1RVMnBzaG5zNWUyUjdBSVhh
            UThWbVJYdkR3Tm01SFhLR1ExWlYyclUKLS0tIFJNZ2NnSXUxb1ViQTFWTFhGRDZE
            M3h2MzZQbWUwa3BRWnlSYlV5cjcrRWcKoYyAPCb005nmpIL4En66lriv1zYSwPCO
            0HRKLNovk6yI6UFruCrpKX/qKlq1uNn8N22Tqv7ckeguuVMIwcWzVQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-06T21:54:14Z"
    mac: ENC[AES256_GCM,data:HYPhjY8pJIxCgwi2Xk0JsceZkHKpYlKVq1ldXxROJT1TOZKhAo8f7xiXEUL+8u6VpSX4S6DEbqJzgQN+rQC3Bfjc8BJIneUdyOj+CX91fPTJz0fry7/jjUpHWvB5Z9HY97VVymwNk+wPI4xdNtR0nxiFha/1rBnaMuBIsALWE24=,iv:cwi8LOKU4PYm4rBIfjowVJTmk7ICtYv8BhxceceRwu8=,tag:LMTDhCyoD31thsfhgTpeKg==,type:str]
    encrypted_regex: ^(data|stringData|((?i).*(API_KEY|TOKEN|SECRET|USER|EMAIL|ZONES|DNSNAMES|CLIENTIP).*))$
    version: 3.11.0
