apiVersion: v1
kind: Secret
metadata:
    name: cloudnative-pg-secret
stringData:
    username: ENC[AES256_GCM,data:F/1gAwC3,iv:xS5OjTolIpmYDD1ZNZxZJVT8Z04hoTAFr5dQcKZcozk=,tag:zDbmjHLKozzXsakX+93m/Q==,type:str]
    password: ENC[AES256_GCM,data:0eTFoFBV7pm/82KtUg8=,iv:1s+snGe+OeHUZRYhEMnfW9nq4NfCT6XHpylygfLS53o=,tag:322ohciEYrpYI/EFunXdJw==,type:str]
    POSTGRES_SUPER_USER: ENC[AES256_GCM,data:5w8i379dqTimP1w=,iv:lpOtB7toRADfZ3a7WBWGmHfriyHSo9k8ER0IiOh+w7M=,tag:8gQWTVvmQOniTSSUDQweIg==,type:str]
    POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:71kvU0pVpqPnk1TPhx5/+xXwtQ==,iv:fxlt2XUuevreRUGtWIXZcMchQE3Qu+v/FMudLUO28jY=,tag:AmRXXyM1X2qQ2SypKpKCCA==,type:str]
sops:
    age:
        - recipient: age1xlls984taykl6jyq0f965lyx66qj6e4cg4wqwrfav258c5gpr44qkwuv3w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAreUFhMzZDdm9RVHNWd2Nz
            bDMxSlBUUGJIaFhFbGJUZGU4UW03RWY3aTNjCjBiNGx6R1N1OUc3a0pOLy83TUMw
            SVFVV2tqQmVFUzhtWDlRQzZzQ0Q4YncKLS0tIHBOUmVVaGZySzIyK1RRZVIzdFR2
            WkNPQndaa0ZWcjJmTXdrWlM4SmRsdUEKcFk8X0TxGDVEM4K1UBOY9tPacVhm7D2R
            YoYEsLAmFkhCGp/P3W5iUWuwQeY5TUHcVWrB5IsVOUavMER0SAfBhw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-05T19:39:59Z"
    mac: ENC[AES256_GCM,data:3RgLjj1zxYfxnw2fEfLbeNx2k06hDqMbMkFxpDmYmNMhVWrDII/yQKquNtRCeAw3ECGdu8KnMbX3X2ruzMxEp9R8uCMin/6l9IdfDdPlIWBwMOQKKuWgYNBkfoIN6SNVTG1v2s1aTYwqFeAq52hOzl/j+WzAJ/9QALw53iLnuUg=,iv:gg5CArOew673aHfQpV1gLwmywbDgc/cDzAxj734OGuw=,tag:UaNMyixLS1drB/A6r1dcBQ==,type:str]
    encrypted_regex: ^(data|stringData|((?i).*(API_KEY|TOKEN|SECRET|USER|EMAIL|ZONES|DNSNAMES|CLIENTIP).*))$
    version: 3.11.0
