---
apiVersion: v1
kind: Secret
metadata:
  name: cloudnative-pg-secret
stringData:
  username: postgres
  password: 6MOa2r3b95lnNOIqhmX/nxWJeSBTxhZD8WA3+ctfurc=
  POSTGRES_SUPER_USER: postgres
  POSTGRES_SUPER_PASS: 6MOa2r3b95lnNOIqhmX/nxWJeSBTxhZD8WA3+ctfurc=
