apiVersion: v1
kind: Secret
metadata:
    name: cloudnative-pg-secret
stringData:
    username: ENC[AES256_GCM,data:SJCBYNKPJ6o=,iv:FoyAXban15kzUiy5fSTh+PEOKsJ3izqU/QSPFV6oUss=,tag:Vj/RfIuc45Zk/3pQnMWJgA==,type:str]
    password: ENC[AES256_GCM,data:55Z+XfHqD8KhKTQY0+8=,iv:2y2nkVn7RxylXWxrLIePPBVFMIMe6+lVVGg2dfhqLy8=,tag:Fnm9HOpqMrNhX7Ytn/hHAQ==,type:str]
    POSTGRES_SUPER_USER: ENC[AES256_GCM,data:hoOE38mRgtY=,iv:Fed8c9ZEv8Plu5Lduj1RaSDk48i60yiqRkN0opyYp+I=,tag:zpWbox1kc+SfwU7/cELzOg==,type:str]
    POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:gjGYSk0b0KOfUhI8ddz3ohs3Rw==,iv:XWJzWVHqOuMf7tndvdriMQxo8rJgKo8h8HoaGCLRWhk=,tag:VRpCf6AYZKDZEdbWQ5KScg==,type:str]
sops:
    age:
        - recipient: age1xlls984taykl6jyq0f965lyx66qj6e4cg4wqwrfav258c5gpr44qkwuv3w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZNk5ra0dSR3J3bU05MkIv
            Y24vNGpyQ1pwVDEweG1CRkYra0ttSk5RN3hZCk93enVRUVROL3M5djZnQk5BOXpR
            eEtxSVVCeTZkenByb3VvNUQxTjZna1kKLS0tIHdROFJuYm9nM3VBQlVXd2RFUmJX
            ZXdzNDZ3M1BkTC9OUzB5cnFVaXdTN0EKkd7qtUsRvb3bnXu+0u2bU1ua8nRyXzsw
            uksWwjLLhonPL7n30wqAp37Zsh4Yq4oeEtl6DuJAeJilXzPC6mqYLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-05T21:31:21Z"
    mac: ENC[AES256_GCM,data:BEMuGslLBKuTr1vWWLs1qg6d5gH+1mZH4kvYQ/KdGtiHy6oConSC3NmdVy0b0tm2bhIGl4MgGhW4YAtZUjwqQYoxbjKkD2DTw3D5oXHwssusbiSK3tnFhpTqZQlq0M2YAfMLH1tskUIFoJ+/fTuFP3FuJXEe5Y44krbKqaKN9g8=,iv:X0v0SmX4m0Kh6JZnHHJSieJGATpZ+ry7cWRNZkY1T9M=,tag:uD3nelWV9tgCzDXIWMFHlA==,type:str]
    encrypted_regex: ^(data|stringData|((?i).*(API_KEY|TOKEN|SECRET|USER|EMAIL|ZONES|DNSNAMES|CLIENTIP).*))$
    version: 3.11.0
