apiVersion: v1
kind: Secret
metadata:
    name: kopia-secret
stringData:
    KOPIA_PASSWORD: ENC[AES256_GCM,data:zhY4OZqyeEINIjk4kHu6GWdx07/s0Cs/rBEb368ubeacZeI/Aa5pIT40DMo=,iv:7Hm/BP5ld/So63we6PJCVOv2n1w2bgCCWi0UpG3S/6I=,tag:BQ7A/aqSh/kWUtIgr0tBzg==,type:str]
    repository.config: ENC[AES256_GCM,data:9Li5+HIjDl6lF7uT19uYVzVk6llSAnVZtFRy5Hv5eApe53yfmDbGaZlwSmqAuGzqDjXmpvd3/5qjBmf4BvArwlO1KBEqLVTXKdu1lpwB0eQn0F5kv8yasCGVpQ3oIXBvVLfxEE5A82ACB2A5tirOORcIwyGwVf40hLB4UdQJBnjlgnG4y36rJXQIDOxj2PqU80jnNN0Q9uAFB1ALXY2k4O7uD9U6Q4/FX1I7TqOqpuFGW/brYh4nDIJtbEzbEUSXg9Azf3uQ8vm2ISuTFlaQKxHNqZ52LMtOVeWunnYmzdoKdumpZnBRO1AucQG98ojFtipB/bMwPK60yBAdnN5n0GQRe1xEeMuX9VeOk/vZKafSF3OfgrzM+RylmhEDYLgrTjJmsucFTCn9my3a0FWk8GyrHySptb9nZ/7qAusj+QNCnMox8/Fn7f0HzC2m5xmThhoEcyTUyyU8h8ZgFkKHus8F6yUYDKSFVH3QqjSVn/esoWPRGf2T+wA/ljHnzI/01rL/UzlnRHI9QNrjM79pmMSB7IIw+Bk3njdduLFsG0RYSTjYKVa3ezXeZ0aZPy6RGHVUMtB4,iv:E9db6IHc9fRbXefLzSpDWxwcyzoPvQ8aC8fd+mcPJlY=,tag:lqd9kfMK/7n6zVq3i3KoqQ==,type:str]
sops:
    age:
        - recipient: age1xlls984taykl6jyq0f965lyx66qj6e4cg4wqwrfav258c5gpr44qkwuv3w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBseVlnWWxrdVFNaXltZ2lF
            ZnhJYXNBR1hNM2EzcFBNcGFCQS9lcXV3cEg4Ck9Sa3Z5WVBka0NRZUVFN2ZoeElV
            M3lEMEFUWFBoTDRKV0M2VFJtYTVOb1EKLS0tIGxkNmJCc0xpdElCckZKVU1heU9i
            Q3haTW5qL2psVzBJMVhVRnY2ajVNRVkKvesCf8YIFQY2VpnwlxR3ejdpIXWdgfZF
            ObIRryl1bUcHq/wSwm8WthXkNWQmuNUnf/5udMIvNAeCRmLYjbfkTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-24T20:49:59Z"
    mac: ENC[AES256_GCM,data:TBUUohNbfFhm4OA4432tOiWfukOUnb9rVxhZQULdV/PXBtqHVAw8DuRYJKP/EEqwock1/wNHg3/bAAEyrFQhcWnQx0oI7LYeUwN9Zqw6kkmBr1puR88x5bt3UHcLw7kcRfMdFkEiSWtl/ohfS4qbPrCCB2yOimYdkeeA9Cnchx0=,iv:iOblt1CEFN6Q9lWqq+zhuTt/OasJMiEWQFXQyE27I6I=,tag:yBpM/hMZ6Kx61OT4Gu8NQg==,type:str]
    encrypted_regex: ^(data|stringData|((?i).*(API_KEY|TOKEN|SECRET|USER|EMAIL|ZONES|DNSNAMES|CLIENTIP).*))$
    version: 3.12.2
