apiVersion: v1
kind: Secret
metadata:
    name: kopia-secret
stringData:
    KOPIA_PASSWORD: ENC[AES256_GCM,data:DHwxt9vV/ap5Bp1H0+gGhER8kLF8Y47kB4lOht+uI8xz+61JpJiu2fndDRU=,iv:L04ubzDL0aYxpYAayanpDoGP9qLMx4BQIM+SiX0zzD4=,tag:39en50AQX6FIYrWg4OvPug==,type:str]
    repository.config: ENC[AES256_GCM,data:kYE842Tj/ReucpL3qrlzlbnQ4o6O2FFn2xyRtNjuFLxjHemEKxJumuM0OqGqFhl7yG0jVPepsrB5Cf/fGk/EmyOmtJj58lmhGiDpylB11zZz68jDw1hlcn1/8U8joBCds7WUTG9kAD/XZfMzA1GN8DkS2xDql3/c2s6LnFprilKTt0rR8Y9kJp3HiU8+pbiUUre7XcEEPOM2MKa5jxNrfn6127JLHVdCwAJrwdPdQHqaABMYKvpVuBEj77nfvw4Fn8np5HrEGJV1ldtqjdtGh4ogJfh4VzCZcUu/B/zJm3QFpg0+J3YgZyzt0Jgdy5Z35F0n6QEVh2DYqoCZKdSCgw6uqCSgkiy2qkt9k3gapVsHbU9VCrTPgqYXjvcDsLAi+ciqk1BKoaf5FuNkW0MSXAdn1vNGmsds8Ybd9x3pPmxBfux6+nBram3QDuM9L+/rHrx2pF0T0wr83tAIeRgt1YOxKUQeumRAGGa7JamYOAqAKwLJGayT0x7jdGWzpGiiKJ87mcvwakFTr0AkSSkQGIz21h9S1OHnuXexCNuxM9P77BE5pTacRAOj/dPvIoleHwh9bKH19qsEqg73CnrrdXMGX2APckg=,iv:LPHj2S5f1uZeU689kLPSgaaNO7jlMBrokzJT3awuXB8=,tag:X+sXSmxfNN92r6lnU0ikBw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPVFo2dm1TN1NtZlNTUEIx
            RnJWLzlnY0VuSDMxZGxnQ1BYelZjZXduK0RBCmtjUFBhL2ZBM2JUamRFWU94TDJY
            dEtpdytvTUo4ZURXTHBrU2dCaEV3N2MKLS0tIFhwQmNoUy83NDhCd3NYTi9UQXV2
            UTVhUnhmOE9mb2krZWk3dEc4V1JQQ3MKnHV8pz27crYm8iZLIwsGJ9Jry6Uw/VNB
            mr9w7EO5aZ3V4bu9n4fc6PLOl1w4vSHYVpmUbKu52G6vhaeFeNjzPA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xlls984taykl6jyq0f965lyx66qj6e4cg4wqwrfav258c5gpr44qkwuv3w
    encrypted_regex: ^(data|stringData|((?i).*(API_KEY|TOKEN|SECRET|USER|EMAIL|ZONES|DNSNAMES|CLIENTIP).*))$
    lastmodified: "2026-08-03T21:45:50Z"
    mac: ENC[AES256_GCM,data:CTfXsv3hIv8R257Hoy//O1AMYACTtgBsMfm3i6P8OEAdqd94QInqKtKnPkcY89ToDWxhoppswOcCfItEkdNR0MzFwh+6vojqHh9rwvvAaOEtPnSXQtpnMBddFbbG4Qu9bI3xswuNoIzzNMVgbEasBd0+RLkckodn36Rb9bxM3Cg=,iv:oP5WLx7SfbpObojqVIz/I6rX0FW1FgDjzKnmnRHyPJo=,tag:WJV16hiFXsCp/jQPsEthZQ==,type:str]
    version: 3.13.3
