---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
components:
  - ../../../components/common
resources:
  # - gatus/ks.yaml
  - grafana/ks.yaml
  - loki/ks.yaml
  - promtail/ks.yaml
  - tempo/ks.yaml
  - victoria-metrics/ks.yaml
patches:
    - # Patch to set the pod security policy to privileged. ~1 is escape for /
      patch: |
        - op: add
          path: /metadata/labels/pod-security.kubernetes.io~1enforce 
          value: privileged
      target:
        kind: Namespace

