---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
components:
  - ../../../components/common
resources:
  - gatus/ks.yaml
  - grafana/ks.yaml
  - loki/ks.yaml
  - promtail/ks.yaml
  - tempo/ks.yaml
  - victoria-metrics/ks.yaml
patches:
    - # Patch to set the pod security policy to privileged.
      patch: |
        - op: add
          path: /metadata/labels
          value:
            pod-security.kubernetes.io/enforce: privileged
            pod-security.kubernetes.io/warn: privileged
            pod-security.kubernetes.io/audit: privileged
      target:
        kind: Namespace

