---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 15m
  chart:
    spec:
      chart: longhorn
      version: "1.11.0"
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  values:
    persistence:
      defaultClass: true
      reclaimPolicy: Delete
      recurringJobSelector:
        enable: false
    ingress:
      enabled: false
    defaultSettings:
      autoCleanupSystemGeneratedSnapshot: true
      autoCleanupRecurringJobBackupSnapshot: true
      concurrentAutomaticEngineUpgradePerNodeLimit: "1"
      autoCleanupSnapshotWhenDeleteBackup: true
      autoCleanupSnapshotAfterOnDemandBackupCompleted: true
      rwxVolumeFastFailover: true
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        memory: 256Mi
