---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: cleanup-trim
spec:
  cron: "0 3 * * *" # Run at 3 AM daily
  task: "filesystem-trim"
  retain: 1
  concurrency: 1
  groups:
    - trim
