---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  selector:
    matchLabels:
      app: longhorn-manager
  namespaceSelector:
    matchNames:
      - longhorn-system
  endpoints:
    - port: manager
      interval: 30s
      path: /metrics
      metricRelabelConfigs:
        - sourceLabels:
            - __name__
          action: drop
          regex: "longhorn_rest_client_(rate_limiter_latency|request_latency)_seconds_bucket"
