apiVersion: v1
kind: Secret
metadata:
    name: atuin
stringData:
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:3+FrsxKT+zgeAxINuxF1bH/2LAcE41tIpTkNrBRAjTN1CQ==,iv:KWQ6iV4tUyYFyTwnNjkfEAPnpTsv6dYCWBKr2z8MrEE=,tag:MNxQVUUJ51vrK4alOI8veA==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:H+xcibM=,iv:uaygqnifM+e2ogG6B6YzhwUbeX5lx+xCxNhpl5tbd1w=,tag:88+JBQr4Olxb6ippwgkR+g==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:ZvzL3NU=,iv:5cWMD5Qut8L3UYd8VVcYoQjwYdq6Ioydl0bWCbvwj6Q=,tag:x/P8brNuUPY7oAFLTciezQ==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:Ud9xpsmuoMEugzJATyh+hGlHDvnDN4pHoNUHqBkyJlzhtQaBX4609TNVZ4jVbuGL+iVEzpAPoRPc0hEeZPmJGg==,iv:J6w07vlSz/Xk8eW74fDVVar+oUfTsGvgSc3GSjAAt7Y=,tag:mYrIswR+37e+f4n89gRP4A==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:rYCUoJzb430jWP3YVHoABZUM0pKuW3DvvRPVVGt4/JcSlP2rfUzfmPiY5kc=,iv:5HV2cwF9LRTlqbCsEmPS5vNHlwW4Er0BeTfLerkkDU4=,tag:aYQxO+GKS2fwcODE12+VHQ==,type:str]
    ATUIN_DB_URI: ENC[AES256_GCM,data:cKRKxh9Z0Tu4WNDxjb8HNXkEKHKvjVIGf0Mlly3LR0qmOje2lGdjh+pVbk7Q/YbxaVAPQ/pHWTcazQSI4beDGmATk2+h+UJW8Gv0wE1I2C2alRVHQjiyTXVJjhm+882XC9eh5kl8YZUbo4ZFFoNUv94JsgtbwuyWD5FhxRBwMQby,iv:+DmTv2cSsRtUovMn8wSnwRMtO9WZnxEKmAlZaWZFXSQ=,tag:/YFPognriZP/vx4HT2s19Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYU3hnVnVzdmhiZ0piYUVp
            TUh4SndTQlFyU2tHZXpXd2sweEYvY3lDOEZVCkg4OFVUa0lQZmo0TW4vMEFQSm45
            TnBmeUxnNEJIZ1dLNmxuYnBwdEJiWWsKLS0tIDc5TnhMU1ZsYWtZNkZYK1VmTmov
            UzBGd0pXdkNaNW15WGQ5NGlqdXlRNkkKrpdSeylfRUMdj851PpGkYypA5CjqihG4
            DAINrl3oXqz86l+faCPioP9S6/snCmjCYI7j/TZQzzclRQFWO000Jg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xlls984taykl6jyq0f965lyx66qj6e4cg4wqwrfav258c5gpr44qkwuv3w
    encrypted_regex: ^(data|stringData|((?i).*(API_KEY|TOKEN|SECRET|USER|EMAIL|ZONES|DNSNAMES|CLIENTIP).*))$
    lastmodified: "2026-08-03T21:45:17Z"
    mac: ENC[AES256_GCM,data:CFqKahU7JTxmZ/QrUY1LaOo3AqVJ8E1bZRjmvs4R2rBfNbMcKO9AtN6oO8okwsiVnLRLvVp4xNLPFF5/2m9zestfBohnwb3f0wvwKTQm7LpvjWZLgfj5gyxnNu336IFIKjE+DvV6lAJlKQqTO4ULhcK2R/hCMop03bBdZui23XI=,iv:2zFH6HKTYJWPOFk7ELlsdcsqeENOi/3oMQqlN2Vyshg=,tag:zDSmbZgfREvxOxyMqlRibA==,type:str]
    version: 3.13.3
