apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: loki
      version: "6.31.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    loki:
      auth_enabled: false

      storage:
        type: "filesystem"
        filesystem:
          chunks_directory: "/data/chunks"
          rules_directory: "/data/rules-temp"

    # Tells Loki to claim a 10Gi volume from Longhorn, mounted at /data
    persistence:
      enabled: true
      storageClassName: longhorn
      size: 10Gi
