---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: network
components:
  - ../../components/namespace
  - ../../components/sops
resources:
  - external-dns/ks.yaml
  - cloudflare-tunnel/ks.yaml
  - gateway-api-crds/ks.yaml
