---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: ${APP}
spec:
  sourcePVC: ${APP}
  trigger:
    schedule: "0 * * * *"
  kopia:
    accessModes:
      - ${VOLSYNC_ACCESSMODES:=ReadWriteOnce}
    compression: zstd-fastest
    copyMethod: Snapshot
    moverSecurityContext:
      runAsUser: ${VOLSYNC_PUID:=568}
      runAsGroup: ${VOLSYNC_PGID:=568}
      fsGroup: ${VOLSYNC_PGID:=568}
    parallelism: 2
    repository: volsync-secret
    retain:
      daily: ${VOLSYNC_RETAIN_DAILY:=14}
      weekly: ${VOLSYNC_RETAIN_WEEKLY:=0}
    storageClassName: ${VOLSYNC_STORAGECLASS:=longhorn}
    volumeSnapshotClassName: ${VOLSYNC_SNAPSHOTCLASS:=longhorn}
