apiVersion: v1
kind: Secret
metadata:
    name: volsync-secret
stringData:
    KOPIA_PASSWORD: ENC[AES256_GCM,data:B4TLF5u/xkgKSgblhdbRulbrhvNDf8XMjYhnJil7onceZKqgTMb3Q7atC/w=,iv:NvmjMi295PBVPzPHd5Zperv3WLebAyXoqspiGpxJn78=,tag:W70KFBkzaMrpegpgPTQPZg==,type:str]
    KOPIA_REPOSITORY: ENC[AES256_GCM,data:Bng4tZsVWMwZDPEifXhskKVu8M4KvitXYrwWTGG4TGY86Nq66HoPCjjsvJnrGkJSq50NT0wo0BzIg5y+2Bx8ZboCZEbwgv3nEXQ4tt0jLI0l3eawbA3/iQ8J9QVgQ63o28vM1JoHykAZjB0q+ZIt637T3Vaq0IQQILdQJtK954fcq0WJULggSC2lpt6qs4TDuTZGx0H9chK8AFDY+Qupwpcp1gmHm5yiQXUa37Z+jqary/6FS7rqbk4LWJvrnyUvbI90vYzNJEI8RZu03donUxXVG9LexniSiVBABmogr1EXwdBZx6tnuIcDNxg91V+naZFr5Wxu9Dl9y0uk5HlRwTbiBTxrg1/YtsZjF29pAI4AaYzdKTuJWRSBYyiZmltzegGm5dtqUR80yALAzEnsLmdIelvFttbfK6rFeTnj9VO2Eqd0iu0BEwtCHwZVOxueSLTxcl7XgjLbttnB/SZubMQFxyScBf00eAJX0KUWzhlqW10H06uyN3gbfLTf2PZdi9DjMBzDkAXImpcc5+Ag/O3agcBbfy+fP4htLYInjBw1EL1hHs/dD3FOy6yeBQKSvFLN6lrP,iv:xl6cphbBcZQkClp21IYMSqUVBQbYqOy5UZZLa+fsYJ0=,tag:acqKJ9CBFncAost40Y76rg==,type:str]
sops:
    age:
        - recipient: age1xlls984taykl6jyq0f965lyx66qj6e4cg4wqwrfav258c5gpr44qkwuv3w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjSXhVNlI2akQrWDEzcnp5
            ZitLM2MwVFZ5a25NZS9vZXdWcFBnZlhkZXdVCnhnODNXOWl2SHFWUTc0ZGk5ZEFw
            ZWozVVBId0t1RHl0eDdlT3BQNzc4aW8KLS0tIElQNFdGUTNiWG1FYVkwbSs1VFU3
            QXlDMWxGZGpVdHhVZDhPb0hGNktrSUEK+t0y1WU2iC9xUUgQ4vERwfJGbX4EoJAO
            WaRAQ2ui5zBvGjrsGaLUlq3RAdEkBj2CLBFE2PzI3572EDrYtrj3ow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-24T22:29:15Z"
    mac: ENC[AES256_GCM,data:2AiWeNtRF5JMcHYVNusU5ntWTF/E33bZx2+AbtNQtIE0IAGnXFbeiol2CDb6245OegoEJN8Prem9YEKeKQK7KTZ6rksQVcOOkRDIk484o6+98rdgbUKNb76B5TR3PyCGa+GjPM+TeIkY8DLKdjI59S2Eq0IVPrzo/3ZDIzrOiI4=,iv:x2xFPwS1LMmgBkif+pog5+WLN3m2KxHuOi3Qn4UHRgM=,tag:Kf1d6V0X70dh6YMt3o1PuA==,type:str]
    encrypted_regex: ^(data|stringData|((?i).*(API_KEY|TOKEN|SECRET|USER|EMAIL|ZONES|DNSNAMES|CLIENTIP).*))$
    version: 3.12.2
