apiVersion: v1
kind: Secret
metadata:
    name: volsync-secret
stringData:
    KOPIA_PASSWORD: ENC[AES256_GCM,data:ICNLAlMh3hGfGbDMjxFGE10fihWu4jlrGjfE8j+rucDKTjVws8ARr6stzWw=,iv:P+UobWy7vbxWZTtDC01LsYp8Oi29ccuAHYeL7sTU0/Q=,tag:P6uKAl8A20qhW61ooPCPgQ==,type:str]
    KOPIA_REPOSITORY: ENC[AES256_GCM,data:Wgc9A+djEfx3RZRNj02aLCPB3RfGRkXNK1LuoKkg23sBKT8qU06Tltaw3qyjRnNr8ja/KbunFGdVSOPdxOOHEA==,iv:1AioJNVoczKZZMPBxH7BKy1h3PgaQaixZ20LgIReWh0=,tag:A9p+g8GJT8VBWU5/OnvoKw==,type:str]
    KOPIA_S3_BUCKET: ENC[AES256_GCM,data:bkTyq5s9JQ==,iv:bLIgwNzdsh5Vin1b1snh7/P/MP5vM42D22Xk6AHGAzQ=,tag:XIxP0ga763i1RboCo5lhuA==,type:str]
    KOPIA_S3_ENDPOINT: ENC[AES256_GCM,data:UUjHxuno6VuHG5Ob7hFC+vIBf8s=,iv:JfihEdUiUUzBdi9A9dkct7UbEtOFF/m7Q4m0DiMdq4U=,tag:M8OCA13IsTcz77+4S2npdw==,type:str]
    AWS_S3_DISABLE_TLS: ENC[AES256_GCM,data:j4pajg==,iv:wjyMgnkPBKZ1GNhdh7KZd0jXWp+q+btTra2io8GAdAE=,tag:deA5mi6OYEtZhIo7WXb+Ew==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:1HABsEjoTOZt0O6NWo3eXqduT58EfseUyvM=,iv:jK3Pn5UDLabcVMZG6ye7nF2YeUqWMlqoQLL8izh95Zc=,tag:6QnEi2ExSwb9n63bAXfdMQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:QN91hRlRLJOOZ42Xn8bfC7DOBSe5bJY5gSBsAfoaM6Nwrp17a3UO1Lx5CgFjTg01GMQxOnKC1+nTdYYPnZpRow==,iv:j6fEC1lvy8/2W4k1SuRhcH+XHJe5nn2B4OprxT6Tbnk=,tag:Jj8KeY92DvDccPiV+1VURA==,type:str]
sops:
    age:
        - recipient: age1xlls984taykl6jyq0f965lyx66qj6e4cg4wqwrfav258c5gpr44qkwuv3w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiN1VMcDIrYmpJZ1ArV0N3
            b2U2Z1lSdkJ0STA4TnNScDlXZnRBVDM1am40CjZDN1lhSWJZVkRTUnVHdVJ0bUZi
            ZmpTd244MGFGQXY0MHE2djNjK29tVDAKLS0tIGZRNGV2ZmFEOHFFT2QxS3puSVFk
            YWFOb2puTTBaVDZqc1krWWFEZzVGTVEKkEoin5OLuD5r15yeNvor14AQNP2cu8Wj
            F3WEhe2yCBHK4r4qqU24palj1UbuIXW5CTKo1ABQZyT26/oNK72J4Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-24T22:58:06Z"
    mac: ENC[AES256_GCM,data:Up4oqgxSrVZsn4SGzkZ3VzSbL/EhliekUJztNSrbgn5TDE6g2ef/uqNz41i9nLBJGUOH03kU6Hb/Yls5CHo7DUqh+YNj97Tu3klwc5wAohF9BWnMunMzA2jacxxM2idy2ezTAF1TgyhMhHW29J/P3+9nIhyerQExHqy2JTvbbbM=,iv:UmSGAhFd0xi4SBEKrqbioGIX8IRViUNQSVx9XPnStDg=,tag:a/65fKcOJ2LC1PDt+X3W3w==,type:str]
    encrypted_regex: ^(data|stringData|((?i).*(API_KEY|TOKEN|SECRET|USER|EMAIL|ZONES|DNSNAMES|CLIENTIP).*))$
    version: 3.12.2
