apiVersion: v1
kind: Secret
metadata:
    name: volsync-secret
stringData:
    KOPIA_PASSWORD: ENC[AES256_GCM,data:2dx985C4IPFv2cIfmAY4g9aSQKSBSd40x9LGZ/TBLylWTkbGZjIEFrH9gS0=,iv:yFNAR++7kEMwEXGpNLbPE/myCgenpxdQxobWyVLuyMY=,tag:lupWzZCVy8UVxcFqTH3BJw==,type:str]
    KOPIA_REPOSITORY: ENC[AES256_GCM,data:T7TzaknY1gJzLn5Q8xLH6LLW9YmunxTqIzC/l2t6GSZVHE/mmKFYTIDWNRzJx0s4SIcLQ16Bv3oYiEA5sVN7Fw==,iv:1/Tkp+7WQlwuj0ap99EDeTuajhb/jfnZJSzZ4iT9wG8=,tag:aYLxdYDMZsvKrxsp/ESytQ==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:/3zbMawdglk/oSMDhRtZtmYTPLx9CG0luc0=,iv:HH0wORX7pZjeiRaLw1I/PZ7o/hfvYbvM2X4aeS26Sv0=,tag:GW1L9Dz8xS3/nS7M91hhiQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:+eqKx4nFAcTbmyzm2Z0jkVH0F8nXq352DNHux0SvjekPnh0AunzSMFxNlXVjLHhJA42PW2fc03OX3wsMYx7Jqw==,iv:3ki87PzRIT/Kyl9sz4WMcs1iGlllFfGtYa99NSMaygM=,tag:wK1cYJxAWI5GbfhyB6XVZA==,type:str]
sops:
    age:
        - recipient: age1xlls984taykl6jyq0f965lyx66qj6e4cg4wqwrfav258c5gpr44qkwuv3w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRUzZBR004ZGpvOUw3WnpK
            TkluaVVYL1A3QVpsdGlGbno0YjdiU3VDOGc4ClJCZjN4VU5WNUlhT0xCY09zY3NT
            SlJTazRsTTZWaDBIdm92WkdkWjNVZVEKLS0tIEpOQ1hrc0tKQmE1MTRFb1RDTUVK
            ZjlyQkpWVjRFWWNCV3ZBTzlmalNKaWsK9QepNChPIV1DrhMZDkhbtBGBu7Chx94p
            oOSLrRxKeHvtWpYQdzT2Z5u4fmK6Ab+yTU6o6iQq4WvgwDcHbanHzg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-24T22:52:38Z"
    mac: ENC[AES256_GCM,data:1Ty5Pf2lbLWzLILT+obDyhXRBcC0r8cgghDOKg/LMVSEL1bZS2eNQ7xBto17DuTCSyfo3tzR0xZvxM35tlZ/s3DsOYCfD+VyRUy0McqFsuUoFtdzRGStgmdmDKaUucxDtJ/lHxSK9hVIzWnSW2B/Ntus1IH8+iNvtKEXs+SeX2M=,iv:vLLZCdCKdenJqbwCvWs4rV2gEwZvcdpq8QcPd2pPF2Q=,tag:5wP5BUrTVs+2weEpgnFqTw==,type:str]
    encrypted_regex: ^(data|stringData|((?i).*(API_KEY|TOKEN|SECRET|USER|EMAIL|ZONES|DNSNAMES|CLIENTIP).*))$
    version: 3.12.2
