---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: snapshot-controller-crds
  namespace: flux-system
spec:
  interval: 12h
  sourceRef:
    kind: GitRepository
    name: external-snapshotter-crds
  path: ./client/config/crd
  prune: false 