---
web:
  port: ${WEB_PORT}
storage:
  type: sqlite
  path: /config/sqlite.db
  caching: true
metrics: true
debug: true
ui:
  title: Status | Gatus
  header: Status
connectivity:
  checker:
    target: 1.1.1.1:53
    interval: 1m
endpoints:
  - name: status
    group: external
    url: https://status.taylan.dev
    interval: 1m
    clinet:
      dns-resolver: tcp://1.1.1.1:53
      insecure: true
      tls:
        renegotiation: freely
    conditions:
      - "len([BODY]) == 0"
  
