---
alerting:
  discord:
    webhook-url: ${DISCORD_WEBHOOK}
    default-alert:
      description: "Health check failed"
      send-on-resolved: true
      failure-threshold: 2
      success-threshold: 2

connectivity:
  checker:
    target: 1.1.1.1:53
    interval: 1m

ui:
  title: Status | Gatus
  header: Status
  link: https://github.com/kondanta
  buttons:
    - name: GitHub
      link: https://github.com/kondanta
    - name: Homelab
      link: https://github.com/kondanta/homelab

metrics: true

storage:
  type: sqlite
  path: /config/sqlite.db
  caching: true

web:
  port: ${WEB_PORT}
