apiVersion: v1
kind: Secret
metadata:
    name: volsync-maintenance-secret
stringData:
    KOPIA_PASSWORD: ENC[AES256_GCM,data:lsmOX4fQxixIP20msBnv5qT8FZOFWgXr7tsVMhPO3VNTJLLP/taLAH4/L30=,iv:7oeaT/aipw+weX7E+F2Zfiflua844bgP+4hxXgoTE94=,tag:qbhFWoCrgehzny+NXPTvkg==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:3lEatv2UlGWhHUIv9TkOTaaMtgLjqKgkWwQ=,iv:hBHFratlUDNKjo+k6CksaPp+1KoewTlvNxU6/dAyDRA=,tag:Tx8ruq4BLGcw9m7l2ETbTQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:YlKCuAdh8/CV/upmgLZ8R+LPrjQya4yy55ZMqwNG+DAA2LZPogVyFs6SAyFvDEbfNoAhnjR9hMxx4MCqwLJYYw==,iv:xZXp6MqbRGDM7cPg16HbETYMkc6NNVWTRenUAnDNsWg=,tag:Jjxha/tLX8PDXtzixLtxHQ==,type:str]
    KOPIA_REPOSITORY: ENC[AES256_GCM,data:OGWE9V59ERJ29U7S,iv:2W0rOheUwa/EOF02KSCFL3avd8otu7nzvmpugpGpwYI=,tag:VGwE3KHC79d1T0DjFkKs3Q==,type:str]
    AWS_S3_ENDPOINT: ENC[AES256_GCM,data:0iZ0m7Sff77hQQg9b8KC5qIy/IyXDytvavAJIitvGDEk/6s/BA==,iv:YIvghlP7k07XA9+IbV8QVFGpPmduMXNXoAxdz6fZx2k=,tag:lKFrZ11SAqTynGtRQZjC9w==,type:str]
    KOPIA_S3_DISABLE_TLS: ENC[AES256_GCM,data:WUBCrg==,iv:CiSPy686aCdElSqjnRxEd3D6Zkew2tZReMqSqfGUsAA=,tag:o85NLJRKzA3H/75EjJKgVQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNbk82S3NOeXNiVVBndjBq
            SWszc1hnckcvSEg0ZkQ5YW9Scm9TWHM5ZzNjCm9EZWFrMUE0V3lNanlrTE9zWGJM
            QzhhbzYvUVlYcGZUSnhrelhVMUJwaUUKLS0tIFA0bjZjaS8yZHd6U0NlNEM0Rkgw
            MXFNQmY3Y0RHRk0yeTVmc3p6ZXMxL2cK4SmsJUFjro1sgAVeJ1XZPz3y6Bg/zDBJ
            zZbtYCehuPY9DMZmu6CtZlrYwdAUraSmtxKHBiCQocrDOG9Ro+DM6Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xlls984taykl6jyq0f965lyx66qj6e4cg4wqwrfav258c5gpr44qkwuv3w
    encrypted_regex: ^(data|stringData|((?i).*(API_KEY|TOKEN|SECRET|USER|EMAIL|ZONES|DNSNAMES|CLIENTIP).*))$
    lastmodified: "2026-08-03T21:45:30Z"
    mac: ENC[AES256_GCM,data:SncHtRB66nvw/rnzGepip9t1PFyD1apIyfPjmgHhLt/zO1+mcmlHcY3VcxseGfdGUqsla8OpalKPhMKsktPIpjUNCHkLHbMrTsyIzNbGHR9yP6/o1vJy+U+OgPgwAnb2fGBmEgQsQ6sRUMo79QDJHtqfxNvM5gOpGkQ5wefm6G8=,iv:/Lw7WPsa9NwC/Bhxy9X7ZLXz+DOlfYg41CxSMNfo33g=,tag:DByFgU8CMoG7J1G9jkevhw==,type:str]
    version: 3.12.2
