apiVersion: v1
kind: Secret
metadata:
    name: volsync-maintenance-secret
stringData:
    KOPIA_PASSWORD: ENC[AES256_GCM,data:be98O85udkkPwu3VA6FKEIKFCafUSC+N+tFWGBLXPwEsJfpysuTC/BdBW20=,iv:scmYI0+tWVTt6ppOU4VAqJjyjy7CjAMbz+t3PHlIaT4=,tag:Xy0lFrv86rMOOxWN31vSxg==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:kmd1SB+RtEEei9wSpCnUr5M/JasumXNIScs=,iv:+acZBbCmqTEKF6oF2IgxlPHAqzypOuc98XeeEgu5kXs=,tag:pPjkctc0MmPnGNUu5rNizQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:G4LaTwG1kxj8A1uBiuDgBlAq5Uw9khSA0TEG7mgq4L8NyUR76nsVqyllzgCyIi27BiG/zrnPuIevJhREVGO6lg==,iv:qr4ErkiN9/UfHb73x+fPWf0D7842pPUU6SrUhZwwVIk=,tag:fh4XAcfoL1ZRZMgtrHW/ZA==,type:str]
    repository.config: ENC[AES256_GCM,data:QiQBYQK0AJmFCv/1VtFFagrYo++46cvseSp3zHvaNKTl3oFC5C3UVhXER05W74QhbzK8UirxTEjauSHnvIY4eBxJI/v1S465Fs928gg0AFMWu1DYuvRVyq6RrZ2CI9rzq28cj80LYovMb8Jdp3k51lyX3fL/VC2BjmeOwi9eLF3SES6c56ja5bOGLG1ASTWKrmCGHvsdcFKOOpeU/vlK6MGEKHT6UfR3f9tuyVE5+Pnh59VEnCbc+J9KbGLn2wJCauLeY4q4jMyO3e7gVobr0hJeGtYCWyRKOKFMlZh3IpjN/T1xuAGQrc+mCPx5QKo0OiZL9ZZgie5gtD9d/ElduALkjv/DCM3dE1CJIMgnWCt25xpQNb/FxOhfHS/EiXm4aVnSROKeNX6oTf2GeUK+fCGE1qP7NY8txhK0E9onUfUZCmQu1dD8iGCyyoZWcSyVgzsDm6ltRwfu4u4mJQePsESVhJT1GgUbMP+8pEFUhJyXKG6ywiUnTZhA4cAOLn/uGfTuaTfzhoWZ6EB/JwJ35O6Ra0NOq8fCwgRbLUgIsimLmZ0IXlGmoRDGdmhxq9wjMBIXRMyx,iv:Gdm8GYy+rjjBLrCTniaCOhQc7XjqNNA71bUMQDZUlgA=,tag:iCAOuT4rJp19g0c5dPSvVg==,type:str]
sops:
    age:
        - recipient: age1xlls984taykl6jyq0f965lyx66qj6e4cg4wqwrfav258c5gpr44qkwuv3w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXMzUwQ3ROWnh2K2U0NGNK
            NU5mVVp4dHBjSGVWcVlTekErWEFlQStEYUJrClh5Z2dteWxqZDNwZFA4cm1NMTR6
            dHUyNTJPaGZuS3BXT0NTaUJHbWx5WUkKLS0tIDJ1MHJPV0dqVlFWb2o4QW51OTF4
            UnhydGFRQktRUFdKZVNsMXh6QUhWQ1UK/Id1J8/qai+ps4SGrN1hWicL+TrT/c3G
            JC8QiH7Dj+dokAcQqykRsEjRHhczNV8g7f7VnL2vgO5dggLmIfbdSg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-24T20:50:17Z"
    mac: ENC[AES256_GCM,data:cU4WLjUKVneilcqymjOu7ylN0Y1D/KApdlPYu+BZ+IcS9IUN0t2PTqU+A0BGceXdXP/1eQCmJGzNtCGB2BJG+ETx/eEwrq4DeLzDdktkxzS5SuL4ptPrMUQ+VzGO4BW8J8W1Gd18hIu1c3VfZBh/D9c2Z6XKko4FLypKL8YeNtU=,iv:j7O0yNg/FRQIgtD2QWYszyxFnzWkNhaYyPTNV8qRCk8=,tag:DSd8rdAma+YB3kq3UmyNfg==,type:str]
    encrypted_regex: ^(data|stringData|((?i).*(API_KEY|TOKEN|SECRET|USER|EMAIL|ZONES|DNSNAMES|CLIENTIP).*))$
    version: 3.12.2
