---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app homebox
spec:
  chartRef:
    kind: OCIRepository
    name: *app
  interval: 15m
  maxHistory: 3
  uninstall:
    keepHistory: false
  install:
    remediation:
      retries: 1
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  driftDetection:
    mode: enabled
    ignore:
      - paths:
          - /spec/containers/resources/limits
        target:
          kind: Pod
  values:
    controllers:
      homebox:
        annotations:
          reloader.stakater.com/auto: "true"
        strategy: Recreate
        containers:
          app:
            image:
              repository: ghcr.io/sysadminsmedia/homebox
              tag: 0.22.3@sha256:b6c1362ab0450ca8fc1a347c13614a0b4f5674e1ecfa9a57a8c456612921842b
            env:
              TZ: Europe/Oslo
              HBOX_LOG_LEVEL: info
              HBOX_LOG_FORMAT: json
              HBOX_WEB_PORT: &port 7745
              HBOX_DATABASE_DRIVER: sqlite3
              HBOX_MODE: production
              HBOX_WEB_HOST: 0.0.0.0
              HBOX_WEB_MAX_UPLOAD_SIZE: 25 # in MB
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}" # homebox
              - configMapRef:
                  name: "{{ .Release.Name }}-currency-config"
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/v1/status
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup: *probes
            resources:
              requests:
                cpu: 15m
                memory: 80M
              limits:
                memory: 256M
            securityContext:
              allowPrivilegeEscalation: false
              capabilities: {drop: ["ALL"]}

    defaultPodOptions:
      securityContext:
        seccompProfile:
          type: RuntimeDefault

    service:
      app:
        controller: *app
        ports:
          http:
            port: *port
    route:
      app:
        annotations:
          gatus.home-operations.com/endpoint: |
            conditions:
              - "[STATUS] == 200"
        hostnames:
          - "{{ .Release.Name }}.taylan.dev"
        parentRefs:
          - name: internal
            namespace: network
            sectionName: https

    persistence:
      data:
        existingClaim: "{{ .Release.Name }}"
        advancedMounts:
          homebox:
            app:
              - path: /data
                readOnly: false
