apiVersion: v1
kind: Secret
metadata:
    name: homebox
stringData:
    HBOX_BARCODE_TOKEN_BARCODESPIDER: ENC[AES256_GCM,data:W9/LTaHORfLOOMgwDJOzTZq7wMQ=,iv:dCozH+6UOP1YDtgm2QP82JvboofZixhGEeLRUJzmwJ4=,tag:ib1SenuPnXbkGqj4Sj+D3Q==,type:str]
    HBOX_OIDC_CLIENT_ID: ENC[AES256_GCM,data:QwKGJLclWlfopkmlH3gCtot0Rvob02eTKLdKu3YiUBw6i9OrO079hQ==,iv:w4B+o8HCuucIKr0iGFF3TxKPKc48l3DgcU8i8mdWMEE=,tag:5FgWOtD2O0LxRuw3pIsmeg==,type:str]
    HBOX_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:+pCrUnx+oeXVlhR//mNy3919lbKIaOkF9oj8e0klszw1RcxFHvx0LIm5Olyfu61C0mD6yaS4/PdZ7Tl9NtLPmSl4/rW1Vpy1T/+AjqpSrYdf8+j4By2YzJ0pzH504teBIe8xOk900+u/Dz6DJPXjioV9amSZcEs4hVPIE8uhG5Q=,iv:WuGhv5/KjXXRJ+puKB3/BHbEdtQHJZ/8NZ6UCNw4fDY=,tag:CN8re+EwZUHX3GEFEoO1Tg==,type:str]
    HBOX_AUTH_API_KEY_PEPPER: ENC[AES256_GCM,data:hgN2/8oxnvyQgiainh2i+0k2BwcfTHFuHEWHXZcHpQ1pZNUoVQyWo2JUApA=,iv:zaNScSep4/YMxwRijMkL14PtjKCu1vCVIyXsSew9e5Q=,tag:1ujg4N6FvZFdRg1+Hns+GQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtU2U3aWRtcjNFdlRGZ2E0
            NVltWFFZVTQrZ00xZ1JNbkN0K0JlVmlGUGtVCnc2Z3pPNmsvWUhweHM3UzdWUDBD
            aVpuWHBUcDlwK3Rpa0FDTzF5OGRNOEUKLS0tIFhIaE1RWUl6VmFpWXZVd080R1lv
            c2xIK1UxTWNYUDRBQmVKOEFPdTEvOFEKMPWqrgaBtLbYRs+5F9R5h0pXxNKK+Uwz
            disLDVTAYqjZ1ENXF3KLIH5mO4YFmmtiXs8aP64LtlwDLViqqrtE8A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xlls984taykl6jyq0f965lyx66qj6e4cg4wqwrfav258c5gpr44qkwuv3w
    encrypted_regex: ^(data|stringData|((?i).*(API_KEY|TOKEN|SECRET|USER|EMAIL|ZONES|DNSNAMES|CLIENTIP).*))$
    lastmodified: "2026-06-15T17:52:33Z"
    mac: ENC[AES256_GCM,data:eQWXd2p09P/ftnJs1OrBlSZB4NGU7a8jHIRMJpe9AshOh9hQtxdbBOcDtsEoma79m/SHq8MtWPAEP4nEG7ju4hBnpj9mJQ/To3DXGDSoxzeQIaQ+lfEh0wG2uhhVkYUZZjAIY6gbfQEg38/PU9k5X2KrIx32LH0suZcEMyuPJuM=,iv:HAx+JXshTDhuunH10OUIrnNgqKbcPbBrIigmdnW7xeE=,tag:ENpVTXQ8K2Wx7mrntJx5zw==,type:str]
    version: 3.13.1
