apiVersion: v1
kind: Secret
metadata:
    name: homebox
stringData:
    HBOX_BARCODE_TOKEN_BARCODESPIDER: ENC[AES256_GCM,data:z1rnalHjktlDmEJFdemVbKfZmTk=,iv:WHY5EMfnilRpB6+fXRvk4tgkZQpTSnJTDc/5zH0vbX8=,tag:/PphnQl1NANhqJxSv5u64Q==,type:str]
    HBOX_OIDC_CLIENT_ID: ENC[AES256_GCM,data:Qhpy1ar7yikJit1jQJ0k55BaD3RLzKGUsI3R/pyqQs5ShxjkduXp8Q==,iv:4PzB/lWBVHg8wDTkKWvoLJ1kYE6hxAZAwp9gLdv9VTg=,tag:3T/+MQH3qLmfO9j8OxS34A==,type:str]
    HBOX_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:Qri26S90omn0aWzl2ZP0Kn+x7BBL8D8Oai+JuIcck5QPIu7mjsqBpzU16fUNXwXUbLrY4InqHWCPSPBpyG36svuGlurgyd3lkPwx95VPbZq/L1H0dgMq7C6Gx2+Ju3QNZxTBdnNbKS/QPZJsvtceBGDmhkNe2gcDfuQlgaSLD5Q=,iv:Q6koWTCHCEIY3WKKxkLfh4+BVeGQMLZBzgR2ZCekvfo=,tag:Rejbl86tLAAPIgc7IJNM4w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArTVBDQjNFN1U5OE5kN1JW
            Mis3V3lNWnFrZDJXZ295Uy9SVEg4RndDL0RRClM1SjRyNWVzSEx4WHFTVEdYc055
            TGdLemplVkI0dlQ0NkYzdkszamhZczgKLS0tIE5vRWdPMnVlblFTSjJ4UnF0YzND
            OCtiWi9rTlVYUXIrWURrK1lmNkxEelkKyl9TdsWFsIns/8c4dhb9K2zpAzqNM7Of
            AEtF7vnS/QnMipqiWY50NhOxt1W43QHRUMzefI/yCNgHnTZUe2SJYw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xlls984taykl6jyq0f965lyx66qj6e4cg4wqwrfav258c5gpr44qkwuv3w
    encrypted_regex: ^(data|stringData|((?i).*(API_KEY|TOKEN|SECRET|USER|EMAIL|ZONES|DNSNAMES|CLIENTIP).*))$
    lastmodified: "2026-05-28T14:52:09Z"
    mac: ENC[AES256_GCM,data:1iCn9/Sd7TCISsi9wioga8meQMAxgyarAO07EHApywnq3W8y/dqBNI23OvdAsi4AR42G8JFX32zAWO1EPFJqnPWf7TwhI/N6r4dqEWJCGsuytwL7GHxzBa6siu92CJCqrXP5a9IEn+7yM0IDD4cpaN4iq3FW4eU48FU3Cf/pu4Q=,iv:98LYokB73ZM7b/513K2S7L/RgH8P9BQo1Jmi4OdTiQ4=,tag:PGkV1soyKb1gV+pLp4E/VA==,type:str]
    version: 3.13.1
