---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: tempo
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 1.24.4
  url: oci://ghcr.io/grafana/helm-charts/tempo
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tempo
spec:
  interval: 15m
  chartRef:
    kind: OCIRepository
    name: tempo
  values:
    tempo:
      reportingEnabled: false

      securityContext:
        fsGroup: 472
        runAsGroup: 472
        runAsUser: 472
        runAsNonRoot: true

      containerSecurityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        readOnlyRootFilesystem: true

      storage:
        trace:
          backend: local
          local:
            path: /var/tempo/traces
          wal:
            path: /var/tempo/wal

      resources:
        requests:
          cpu: 10m
          memory: 128Mi
        limits:
          cpu: 100m
          memory: 256Mi

      distributor:
        enabled: true
      ingester:
        lifecycler:
          ring:
            kvstore:
              store: inmemory
      compactor:
        enabled: true
      metricsGenerator:
        enabled: true
        remoteWriteUrl: http://vmsingle-stack.observability.svc.cluster.local:8428/api/v1/write
        storage:
          path: /var/tempo/metrics

    persistence:
      enabled: true
      storageClassName: longhorn
      size: 10Gi
