---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: tempo
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 1.23.2
  url: oci://ghcr.io/grafana/helm-charts/tempo
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tempo
spec:
  interval: 15m
  chartRef:
    kind: OCIRepository
    name: tempo
  values:
    tempo:
      reportingEnabled: false
      
      securityContext:
        fsGroup: 472
        runAsGroup: 472
        runAsUser: 472
        runAsNonRoot: true

      containerSecurityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        readOnlyRootFilesystem: true

      storage:
        trace:
          backend: local
          local:
            path: /var/tempo/traces

      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 1000m
          memory: 1Gi

    persistence:
      enabled: true
      storageClassName: longhorn
      size: 10Gi

    distributor:
      enabled: false
    ingester:
      enabled: false
    querier:
      enabled: false
    queryFrontend:
      enabled: false
    compactor:
      enabled: false
