---
apiVersion: v1
kind: Service
metadata:
  name: garage
  namespace: network
spec:
  ports:
    - name: s3
      port: 3900
      protocol: TCP
      targetPort: 3900
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: garage
  namespace: network
  labels:
    kubernetes.io/service-name: garage
addressType: IPv4
ports:
  - name: s3
    port: 3900
    protocol: TCP
endpoints:
  - addresses:
      - "10.1.20.51"
