apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: grafana
      version: "8.3.4"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    admin:
      existingSecret: grafana-admin
      secretKey: admin-password
    datasources:
      datasources.yaml:
        secretName: grafana-datasources
        key: datasources.yaml
    persistence:
      enabled: true
      storageClassName: longhorn
      size: 5Gi