apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app grafana
  namespace: &namespace monitoring
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 15m
  path: ./infrastructure/apps/core/grafana/app
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  prune: true
  wait: true
  # This block explicitly tells this Kustomization to use Sops
  # Dunno why it doesn't work from the parent kustomization
  decryption:
    provider: sops
    secretRef:
      name: sops-age
