apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: grafana
  namespace: flux-system
spec:
  interval: 15m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/apps/core/grafana/apps
  prune: true
  wait: true
  # This block explicitly tells this Kustomization to use Sops
  # Dunno why it doesn't work from the parent kustomization
  decryption:
    provider: sops
    secretRef:
      name: sops-age
