---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/prometheusrule_v1.json
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: volsync
spec:
  groups:
    - name: volsync.rules
      rules:
        - alert: VolSyncComponentAbsent
          expr: |-
            absent(up{job="volsync-metrics"})
          annotations:
            summary: >-
              VolSync component has disappeared from Prometheus target discovery
          for: 5m
          labels:
            severity: critical

        - alert: VolSyncVolumeOutOfSync
          expr: |-
            volsync_volume_out_of_sync == 1
          annotations:
            summary: >-
              {{ $labels.obj_namespace }}/{{ $labels.obj_name }} volume is out of sync
          for: 5m
          labels:
            severity: critical

        - alert: VolSyncSnapshotStuck
          expr: |-
            increase(volsync_kopia_snapshot_creation_failure_total{failure_reason="prerequisites_failed"}[2h]) > 20
              and on(obj_name, obj_namespace, role)
            increase(volsync_kopia_operation_success_total[2h]) == 0
          annotations:
            summary: >-
              {{ $labels.obj_namespace }}/{{ $labels.obj_name }} VolSync VolumeSnapshot is
              stuck — prerequisite failures accumulating, manual snapshot cleanup likely required
          for: 10m
          labels:
            severity: warning
