apiVersion: v1
kind: Secret
metadata:
    name: grafana-oidc
stringData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:0uBtRrd6qTN+CKvCXOUd5VMDnPvmRzPQ5V/dspIpKQ9ftvjU7DQN8Q==,iv:UxGJpfrXVbLgOPg16t5YqGiMx65kloF7AeXHsuktvlc=,tag:ImV1gaRam1oIchcaEKxFgg==,type:str]
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:WdQcru65vr37mMDsGtHy/JSAR32tXTrQHdFVR6Vp+/ndSM0wBDu+RHl5hw98SAWLO0JRPX+dPgDB210tUo/WJGk6CLjHeDoU5xI0cC8FKeqcLPoSCwYZYzITqVVJzUWNo7gKq9CVxD++Lp8LLPtbPc0v+JJTtZm6ud6rCusMDak=,iv:n2JCblSOGZHpYTJI5VkDVAojwhs2BctnKqN1x0dplsM=,tag:mOZvvwErt2McjkRqw+vEbw==,type:str]
    GF_AUTH_GENERIC_OAUTH_NAME: ENC[AES256_GCM,data:MPi/9eu7/9of,iv:YXATjbGJfQ7mgBFmcXVfY/ABrjQbNtWjRBUCAh0PUtw=,tag:rY/BX11p+Y5uhnTK2+hs6Q==,type:str]
    GF_AUTH_GENERIC_OAUTH_SCOPES: ENC[AES256_GCM,data:OSjqKsC0O9stH3EKqoYMoeTP/Lw=,iv:gw9/y4HderW6M35PNCNQPoCTgLuFe4SztTjKZvzxIDU=,tag:axJNgprStGbSFCnTNR43tw==,type:str]
    GF_AUTH_GENERIC_OAUTH_AUTH_URL: ENC[AES256_GCM,data:YdL67Bq1Jh/BEXOqSsrG3+WIkabSAUFQBOKjeyme+/YKfxr86b8AgUc3b3sYXZiR,iv:HPBcooWvDpP3lu1vRfj8N7xSj1tzrTmbpXl8QuSiG5A=,tag:FZCOhjxjWUS/7S/tLUi4Bw==,type:str]
    GF_AUTH_GENERIC_OAUTH_TOKEN_URL: ENC[AES256_GCM,data:4q4p3JPAaJ9ergrr23SfKnW/C/+fm2qy5scTAlP/PP14sD74BM+Dwoy8S2E=,iv:pNyA3q6hdDgv1gYCbFtaHjwTp+JUaw5kQ67hpjUxsOQ=,tag:VZDXJQ8FaeopNYl/j82JTA==,type:str]
    GF_AUTH_GENERIC_OAUTH_API_URL: ENC[AES256_GCM,data:+AbZZW0j//BsVE8DS++fMFY82SNyxLjp1pecZs7Iif8qnJHi3R1vKE5Ra5entBY=,iv:90OgIHL54bpw3FHtnlEGEG0s0KGmwOjbymU81LZ6+q0=,tag:BCQaKlN3tNjsSiuMT79PAQ==,type:str]
    GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH: ENC[AES256_GCM,data:VvygLxspqI3S9mn8unp3IcIrEFoW6xhtWHRe4neLC3LySY1XCVleWhEJMyXiwH0lZ/tFcCjRkvaM7UKo,iv:IkEXppJ26u3tlP9b/BF/Fym1okmwkOXdgHEHhgF5dmE=,tag:OKlm1H37w1pjk055xT7oNQ==,type:str]
sops:
    age:
        - recipient: age1xlls984taykl6jyq0f965lyx66qj6e4cg4wqwrfav258c5gpr44qkwuv3w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByQkpFM3NjeUo0VzUraHo5
            OWNtM0krcCtRQ3pvSXlGRDJJeU1WTVdtYkZZCmNUYlJyUkJIZXFadXBSUDV1Z0Vs
            UTNEcjJHbmt5SEhUU0h2d1pvV2FvY1kKLS0tIEpSTFhXbytaa2dXZFNjRWNTTzR0
            Vmh6c1YxS0tKZ09XSUVvamlyTkZVTHcKdJgd3dm80Q9wIQ7SVONBsb+IC0Z05c9F
            YQ+pdnkbD3l85P6wxix1ZsQ5Uu+bm/Va1RkS9OjBvDI1UAqWML0TzA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-17T21:03:55Z"
    mac: ENC[AES256_GCM,data:O3DhQXRBw9nIlxsenJUWHxpHWHE4Kz5vLUA9PzIsNOwIpoM65/eV132rjzALY2L13CWAwqxwzBR5gWEjkcNvYod13EwSqAfv7BbMfw/wlmlL9eHoQhB3ubMTQmGWnN50NcthvVCbBZ52dbK5XskMy1dJKdSg+xpw9Mz7hgpWJTI=,iv:as4sYc5gg+hR6/LjBHhJA1n635BLRbfAd9uSxFnTDzQ=,tag:21agO2dSLbuerFoelt9gQw==,type:str]
    encrypted_regex: ^(data|stringData|((?i).*(API_KEY|TOKEN|SECRET|USER|EMAIL|ZONES|DNSNAMES|CLIENTIP).*))$
    version: 3.12.2
