apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: main-pool
  namespace: metallb-system
  annotations:
    kustomize.toolkit.fluxcd.io/depends-on: "metallb-system/metallb"
spec:
  addresses:
    - 10.1.20.200-10.1.20.220
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: main-l2
  namespace: metallb-system
  annotations:
    kustomize.toolkit.fluxcd.io/depends-on: "metallb-system/metallb"
spec:
  ipAddressPools:
    - main-pool
