apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: envoy-gateway
  namespace: observability
spec:
  namespaceSelector:
    matchNames:
      - envoy-gateway-system
  selector:
    matchLabels:
      app.kubernetes.io/name: gateway-helm
  podMetricsEndpoints:
    - path: /metrics
      port: metrics
