apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reflector
  namespace: reflector
spec:
  interval: 5m
  releaseName: reflector
  chart:
    spec:
      chart: reflector
      version: "7.1.230"
      sourceRef:
        kind: HelmRepository
        name: emberstack
        namespace: flux-system
  install:
    createNamespace: true
  values:
    replicaCount: 1
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
