---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: freshrss
spec:
  chartRef:
    kind: OCIRepository
    name: freshrss
  interval: 1h
  values:
    controllers:
      freshrss:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: freshrss/freshrss
              tag: 1.28.0@sha256:5664f42e37e7101c824806d8f73cbc97c8f406ce043bbdb8d39d4ff1e7f2ad11
            env:
              CRON_MIN: "*"
              DOMAIN: freshrss.taylan.dev
              LISTEN: &port 8080
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 128Mi
    service:
      app:
        ports:
          http:
            port: *port
    route:
      app:
        annotations:
          gatus.home-operations.com/endpoint: |
            conditions:
              - "[STATUS] == 200"
        hostnames:
          - "{{ .Release.Name }}.taylan.dev"
        parentRefs:
          - name: external
            namespace: network
            sectionName: https
    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
        advancedMounts:
          freshrss:
            app:
              - path: /var/www/FreshRSS/data
                subPath: data
                readOnly: false
              - path: /var/www/FreshRSS/extensions
                subPath: extensions
                readOnly: false
