---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
spec:
  instances: 3 # needs 3 instaces for r - rw setting
  # renovate: datasource=docker depName=ghcr.io/cloudnative-pg/postgresql
  imageName: ghcr.io/cloudnative-pg/postgresql:18.1-standard-trixie@sha256:9b352c7e9f1095e9567c537e058d49d8e1a6495ee56ed8dbd832d602e689ccc6
  primaryUpdateStrategy: unsupervised
  storage:
    size: 15Gi
    storageClass: longhorn
  enableSuperuserAccess: true
  superuserSecret:
    name: cloudnative-pg-secret
  resources:
    requests:
      cpu: 100m
      memory: 384Mi
    limits:
      cpu: 1
      memory: 786Gi
  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname
    podAntiAffinityType: required
    nodeSelector:
      kubernetes.io/arch: amd64
  postgresql:
    enableAlterSystem: true
    parameters:
      max_connections: 100
      random_page_cost: "1.1"
      shared_buffers: 192MB
      work_mem: 4MB
      effective_cache_size: 512MB
  monitoring:
    enablePodMonitor: true
