kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: capacitor-gitrepo-reader
rules:
  - apiGroups: ["source.toolkit.fluxcd.io"]
    resources: ["gitrepositories", "gitrepositories/status"]
    verbs: ["get", "list", "watch"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: capacitor-gitrepo-reader-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: capacitor-gitrepo-reader
subjects:
  - kind: ServiceAccount
    name: capacitor
    namespace: flux-system
