---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cf-dns-secret.sops.yaml
  - helmrelease.yaml
  - prometheusrule.yaml
