---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: app-template
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 4.5.0
  url: oci://ghcr.io/bjw-s-labs/helm/app-template
---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name satisfactory
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
  dependsOn:
    - name: longhorn
      namespace: longhorn-system
  install:
    replace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      strategy: rollback
    cleanupOnFail: true
  uninstall:
    keepHistory: false
  interval: 15m

  values:
    controllers:
      satisfactory:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        replicas: 1
        containers:
          app:
            nameOverride: *name
            image:
              repository: docker.io/wolveix/satisfactory-server
              tag: v1.9.10@sha256:e103700ae6ae4c50f19dac80eadb2a805c5b885e179ae2a40850e967bf189efd
            resources:
              requests:
                memory: 6Gi
              limits:
                memory: 12Gi
                
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities:
                drop:
                  - ALL
                  
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
                
            env:
              TZ: "Europe/Oslo"
              ROOTLESS: "true"
              AUTOPAUSE: "true"
              AUTOSAVEINTERVAL: "60"
              AUTOSAVENUM: "30"
              AUTOSAVEONDISCONNECT: "true"
              CRASHREPORT: "false"
              MAXPLAYERS: "4"
              MAXTICKRATE: "120" # default is a low 30
              NETWORKQUALITY: "3" # 0-3, 3 is Ultra (default)
              TIMEOUT: "300"
              
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000 
        fsGroup: 1000
        fsGroupChangePolicy: Always

    service:
      app:
        controller: *name
        type: LoadBalancer
        annotations:
          external-dns.alpha.kubernetes.io/hostname: satisfactory.taylan.dev
          lbipam.cilium.io/ips: 10.1.20.70
        ports:
          game-udp:
            primary: true
            port: 7777
            protocol: UDP
          game-tcp:
            port: 7777
            protocol: TCP
          messaging-tcp:
            port: 8888
            protocol: TCP
    persistence:
      data:
        existingClaim: satisfactory-data
        globalMounts:
          - path: /config
      game:
        existingClaim: satisfactory-game
        globalMounts:
          - subPath: game
            path: /config/gamefiles

