---
services:
  smartctl-exporter:
    # renovate: datasource=docker depName=ghcr.io/kondanta/homelab/metal/smartctl-exporter
    image: ghcr.io/kondanta/homelab/metal/smartctl-exporter:0.14.0
    container_name: smartctl-exporter
    restart: unless-stopped
    privileged: true
    ports:
      - "9633:9633"
