---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/common-4.4.0/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: seedboxapi
spec:
  chartRef:
    kind: OCIRepository
    name: qbittorrent
  interval: 1h
  values:
    controllers:
      seedboxapi:
        annotations:
          reloader.stakater.com/auto: "false"
        containers:
          app:
            image:
              repository: ghcr.io/gavinmcfall/seedboxapi
              tag: v1.0.3@sha256:352075e2b98854cd6a451404a12bd0c517eac4e1224243b6f4793de98b4f9a69
            env:
              interval: "1"
              METRICS_PORT: "9000"
              mam_id:
                valueFrom:
                  secretKeyRef:
                    name: seedboxapi-secret
                    key: MAM_ID
            securityContext:
              runAsUser: 568
              runAsGroup: 568
              runAsNonRoot: true
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities:
                drop:
                  - ALL
    service:
      seedboxapi-metrics:
        controller: seedboxapi
        ports:
          metrics:
            port: 9000

    serviceMonitor:
      seedboxapi:
        serviceName: seedboxapi-metrics
        endpoints:
          - port: metrics
            scheme: http
            path: /metrics
            interval: 1m

    persistence:
      config:
        enabled: true
        existingClaim: "seedboxapi"
        advancedMounts:
          seedboxapi:
            app:
              - path: /config
