---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: seedboxapi
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: seedboxapi
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: observability
