---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyseerr
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: jellyseer
  values:
    controllers:
      app:
        containers:
          main:
            image:
              repository: fallenbagel/jellyseerr
              tag: 2.7.3@sha256:4538137bc5af902dece165f2bf73776d9cf4eafb6dd714670724af8f3eb77764
            env:
              TZ: Europe/Oslo
              LOG_LEVEL: info
              JELLYSEER__INSTANCE_NAME: &name Jellyseerr
              NAME: *name
              INSTANCE_NAME: *name
              CONFIG_DIRECTORY: /config
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/v1/status
                    port: &port 5055
                    initialDelaySeconds: 0
                    periodSeconds: 10
                    timeoutSeconds: 1
                    failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 10m
                memory: 250Mi
              limits:
                memory: 500Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001 # media-user
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: {type: RuntimeDefault}
    service:
      app:
        ports:
          http:
            port: *port
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.taylan.dev"
        parentRefs:
          - name: external
            namespace: network
    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
        globalMounts:
          - path: /config
            subPath: jellyseerr
