---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app audiobookrequest
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: *app
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      audiobookrequest:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: markbeep/audiobookrequest
              tag: 1
            env:
              TZ: Europe/Oslo
              LOG_LEVEL: "info"
              ABR_APP__PORT: &port 8000
              ABR_DB__USE_POSTGRES: false
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: *port
                  initialDelaySeconds: 30
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 15m
                memory: 145M
              limits:
                memory: 196M
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001 # media-user
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        controller: *app
        ports:
          http:
            port: *port
    route:
      app:
        hostnames:
          - "abr.taylan.dev"
        parentRefs:
          - name: external
            namespace: network
            sectionName: https
          - name: internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port
    persistence:
      config:
        existingClaim: *app
        globalMounts:
          - path: /config
