apiVersion: v1
kind: Secret
metadata:
    name: audiobookrequest-secret
stringData:
    ABR_APP__INIT_ROOT_USERNAME: ENC[AES256_GCM,data:+Sg3lk8=,iv:zv8hBgO+uh7ukUMMA7SmZD5YbNlDHRf+ETdqeF+LfAo=,tag:RcKjLRTCYCEY5kCVA3ti4g==,type:str]
    ABR_APP__INIT_ROOT_PASSWORD: ENC[AES256_GCM,data:DyNwVAkW4lyx41TqFYgwHp1S5Abt27dzH9A/fIV3/2Gr1jMMKDYkTvsM8Zg=,iv:8OU8Hbf6as8BXKEO0WN+j+eP9WqE5hC6MCseD46LWnk=,tag:/j6Pg9jqrieEMsPKyqRZ6w==,type:str]
sops:
    age:
        - recipient: age1xlls984taykl6jyq0f965lyx66qj6e4cg4wqwrfav258c5gpr44qkwuv3w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRcDZSWDhybVdXN21KVWxh
            QmczZUw2QXJhU1J4K2MwbkVXaGZML1NrZ0NzCnZzb2pFOUNERWtPaXhMN2drS1hR
            ZDhUTGh4VUp4dlE3RWVCZ0RtN3NSdncKLS0tIEs4SFhoeUF3K09yaTczeVVLUHlO
            OTdqMzFCcFJYazhHRDg0Z1RNWFIvVzgKTs77mrSZUF8GOJOAZqmfx0DSLYO7/9/H
            2xwdN2jv+OpNCzcnARrGj1DoLMlkBAo5QMYzqSlSZtnhvla5PSSbsw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-01T21:56:33Z"
    mac: ENC[AES256_GCM,data:8gp6mS16oskjTtJvGMDoD7ral6X2A3WYrffk1bT1HfqsSSiGP0C7E507J+u57TSgCYkhHpdbU26EdVIk9JlQeROyoN4q+DYxn48C7/SE6CCgbOYHAfA2ucD3J7+GhbSBBoW7sdvMlVigwDQGEcnbY2DydNeVuoVlLAKRAkDPz1U=,iv:ygEsJuXJqZiCIwnFGqLIVapDePc9Sqdt5JgPCfM9gwU=,tag:aH7a+v33pDBW3JPeMmQ5/A==,type:str]
    encrypted_regex: ^(data|stringData|((?i).*(API_KEY|TOKEN|SECRET|USER|EMAIL|ZONES|DNSNAMES|CLIENTIP).*))$
    version: 3.12.2
