apiVersion: v1
kind: Secret
metadata:
    name: chaski-secret
stringData:
    DISCORD_WEBHOOK_ID: ENC[AES256_GCM,data:nttoQb9kwLGTezALlodAYOOaCQ==,iv:w5Sp9MGFm4anuCx2rXL3HzshXPRToRDhLZfiDAMAcHI=,tag:8dFR1UBP/pLcuXCDCgPp+A==,type:str]
    DISCORD_WEBHOOK_TOKEN: ENC[AES256_GCM,data:i9kXyfnNzh0XLF6hPSjqfFyzXP6lS+bphNb6XbdpBrtyZNyQZJy3ENT3dlya3f9H9F4EzrpBZNywm5smurW7/xqqk6o=,iv:qtOGPBvLhTJU5vfvezN4bUtZ+oGMQZcKKRkoDlJWCso=,tag:6y4mjMnDYSLo0XDvg6tuvg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxcUo0RVQ0K2MvK0lRSHFU
            K1BNZXcwUnZKc3JEa2VML1RXcTdNRHRYdVhRCndRWEhCUm9zNy9xdzZiaGFZblhp
            OHdlVjBObHZJWDdnZk9Cemlwc2s2MncKLS0tIFVWTHJuQUxpN01XakVXbDhJTHJP
            OU1HaFZERWVLMzEyK2UxVTk4S0N0b0kKM8kJZWE3mX3+21ixGcGtQbHDzR4pRC6u
            RR+0lPnNADhCpCIbiKFoeztni6sufYTJ5d5i0oKUVhsBnJNhgTnJYw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xlls984taykl6jyq0f965lyx66qj6e4cg4wqwrfav258c5gpr44qkwuv3w
    encrypted_regex: ^(data|stringData|((?i).*(API_KEY|TOKEN|SECRET|USER|EMAIL|ZONES|DNSNAMES|CLIENTIP).*))$
    lastmodified: "2026-06-25T21:06:08Z"
    mac: ENC[AES256_GCM,data:Mu4aE0WNaSmHbJdBGxwLfR4v6vi1k3uC5jaX0BK5MUBihoJJiXJ4rsrx0V6zgcY5/XprTtgv0/cCJROnUpaGgzML3/WNWMjH4gaqsKkp5cBw9uJuAtJSo8WTguldEaSJsyc2xFUJTGsFJ75Az4Mp/gy1VTmMhqqdCevmyrc9D6k=,iv:FOZ8R4RtRXFC4gz+/mBhVjTEeHKQSt2yYRF4yPsSN0M=,tag:1VQXsFMu21dItHD+JZSqpg==,type:str]
    version: 3.13.1
