apiVersion: v1
kind: Secret
metadata:
    name: paperless-ngx
stringData:
    PAPERLESS_DBUSER: ENC[AES256_GCM,data:p9X7Fl/2FGRt,iv:BhWX40jN1yn3BWBvjH+Ym+OhzqSBNA8OYciX8tSGSpQ=,tag:4PqRRgA0N6dLXoqLJRgXMQ==,type:str]
    PAPERLESS_DBPASS: ENC[AES256_GCM,data:c6UoiMhEtkIG5hIJcfOa9V+7t1S7GBfzeFjoV9bDamLMdebLYBZ3tJtdVuo=,iv:oL1L+DjQoIAXDVRBJdQJSIHpG5A0VZxuyOrTVZMmuKU=,tag:nIVcZT+3rtuGz3BXRRSkbQ==,type:str]
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:s4IbdqyP2QRCG2DC+mXCPP7ulk0nMTvAfuvOgbfG+U1ACtGyAEfZSyBRwk9HlFhdJeyzvBZYUysSx5Q4nlJl0w==,iv:pKwHF4LYTEbcFiMt0VPZhKFh/AHoBXoARpuY0BD+7eI=,tag:Fz5q7l/r178h2OgqssC9Zw==,type:str]
    PAPERLESS_SOCIALACCOUNT_PROVIDERS: ENC[AES256_GCM,data:KEqDi79NfM8Bh8sPai0uAOiDrHJ5EaOSW4qJ3/NofOk4aX2jlDZacVP70EPfS0p67x0Oc2luTkYagwKDufcnlVO05UFKKJzTxwsQPHghephnZyMjxCic2Al8o1E4dB+c+LoLrkwBr0sPK37q1E//iBZIGLx2lN/2GTxsQxn6vUeqRM/4hjpJK0ua56cztHLmZaG1KzVtcRvsZtklQ3CGhql7v3tSl6RamL8+PEYCzBzpKEtbeaY5gF1DGaQ6gJ+Dv63UgA1gDZ8VeEATB0PNIzefeAJj8rSOHTK/S4yK1XOxpvNcEYnYBxIBfbZse2+l55Ar/BQL4bWwOEszX8Ct8TAjAV5FiL7tJVX1xU0nmVohg73ldpfpx808sw7vzrhJSdAYAAqn2gywnjxQ2ZUUFpvNwLWlsHGq1tTU8gpEAuRVRveBuXuWvkv+dIXOjqxYrDntczz3pmiyVTNNCj3J9uB24RkhhAuq0DJzVA==,iv:h2qrERjRT7Zx+1LXFLfPvNHJnqld01XIUqZl3l0XvhE=,tag:pgB8ejyPzoCUsv6IyCBUEg==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:gEIDpSdEY4hqP7J+sZsj,iv:vbUYFWOn0xVBhULqg5c/W52efH/7iFXNHkA3fEy7Ycg=,tag:cThg1mzA4OZ9gh8fd8OfKw==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:7zyjV2PIZ79Z,iv:OJZhLjXbK8OxllNZmzHvf3bYgB5g0S3CxRgEHzEzUTc=,tag:t/HrQQ5xSVrnyq5fnYCdvQ==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:ZT6WyDSSai3/TPiH0TyWbwy6UWmFCdWz8/T1C4o/T37HpWUMCdHzAYO2uyo=,iv:pxefDqNTnjSAagKyLJ5QjNEH1GoGS6sBwrL6CDftYmg=,tag:XuxVTfG1QoYdYPRbkzCUdw==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:wI2FC2XbIG8N,iv:79MEiN0SQ+eHEzBMOOeNwxGgul9SafxLUTq3XFsqCs0=,tag:l+dN10+IrYdsmZLWKXRQXA==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:SDq7m2E0xZ0ER4qXFxLSpkQhYtZ5DEiVY76RbJHm96KrSbD4Ym71D4SlWlc=,iv:F2hpOHDgnxAB8lGveZ59CP1s9xh/mS+NZcZlwZxO8ow=,tag:Co6yV0RNiVrFKJJ2tDT/Fg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2QmZDTWJhaFlDRlVzd2hQ
            eEpLSHAvNlVVdDlLdzFQOXZsN3lyQmxydHhVCnkwTjVsYmNjUUtkcTZ5VWdjZVg0
            QzBEZUdsM2lOZGpNNzFLZGRzNVpYYm8KLS0tIFJzeUpLYWlKL2Nya3FjTzZKSkZo
            YnBrcWtCS096cG8yMExwZ2Vvck1vRHMKCcfTibDUp/xxvetJV1kPJKY/imXXa0iI
            YnAKXe4cmhS87rXmuBl/Cbm22jIcFW7HWYGpI5sFgqcssSYCbCJ08w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xlls984taykl6jyq0f965lyx66qj6e4cg4wqwrfav258c5gpr44qkwuv3w
    encrypted_regex: ^(data|stringData|((?i).*(API_KEY|TOKEN|SECRET|USER|EMAIL|ZONES|DNSNAMES|CLIENTIP).*))$
    lastmodified: "2026-06-07T23:41:51Z"
    mac: ENC[AES256_GCM,data:MkDB0iLkuzvIUJ4z5K+ojAjdY9WdgwQytTSGP8PCfdEM2G1uLsO1ontAFN0oyfyensZ1IWMx279dcV6lD5KYNmpFODcw0rfbZA6X3HVDGEwwsVpS9+tU35vNYqFSN6pFGwv2Nl+4+aAQisHWSPNdPYtxHkY3KEoOyHKtyBPyd0U=,iv:uzE1wdemF3kwa8NRxxlldJlU88JpdcHu/e4XRlNQf0s=,tag:QSRrFDABw45OBllWqOQcCw==,type:str]
    version: 3.13.1
