apiVersion: v1
kind: Secret
metadata:
    name: rreading-glasses-secret
stringData:
    HARDCOVER_API_KEY: ENC[AES256_GCM,data:L576rxet8m1ueql6ks2KGFKjqvMEE4XZjwT4Q9HVfZTKVg8c/i9cLO6KRJxSIwskh4y7/fofwb4bSQ==,iv:5IasE7ILIkNg9/PSWbmxDth0Es7REAvb2Wf3mYDgQ9k=,tag:TSTW0AV+piFkbXXFPAqgSw==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:4KTJd+e0TAvdu8KoBT6V9g==,iv:YRHzLFJOnNgssUG89Xk/J6cm4ACnNxhsFOHxtqKYQvQ=,tag:bFe/la6lHuKOBlf2ytpCBQ==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:0KdUCXSvq2D/fjtEOn+kbqjAhLBMbYwiiOOZUtVv05K+bQ==,iv:oAXsZ4BE3ovoMJeMKrbqhKyYoD2ml3bTRa0PJzcJUdI=,tag:DarV/uSxxIqXqNPkKtQEzw==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:TRVmqZbG2BIpNPJzawE3yLkMYpc7SO5Wz1F4Wf3C5v2MIBzTcsuxRppzW8E=,iv:BJPD8EbN7i/ekxuRJgKIEwsoEV40ZmSI9heuUpmNip4=,tag:jE4G6QToc4tlMrssd6/Ffw==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:ja872pmtgyPoLSAmeu8GF0sAzRz+M0ZnLNik7hR+8rD0QZqPRCVqj3yaXRs=,iv:VP9Vhk65+cvaaMgqVB5aRu86AkXTiFrz+38NP4DF3iQ=,tag:fahqLWBqbeGUyD5b5lvYJw==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:5oKrzK2xdj55/vvAnqQQMA==,iv:lMKQdKn7P93itpbsdh5GVKuqLVRN3MvRa/E7WDpO5Nc=,tag:+BcHGHPMdubNYGnPL32qXw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBidGk3YWNLR281RWF5Q3pR
            Z3YzSTJoamVUbmMyeERubVZGQkx2WCtvOUJnCk1jSVZwUm11NXZvcW9POHhMMHVw
            bXAxRUdnR010cjZoLzFUL21sWE1ORmsKLS0tIDFsQXZvZHQzemRyOFBUVXRNcDlx
            dWVqUlp4WlA5WjVLNVc0a0EyV2JucDgKEcvfoPzR+tYPTYrTastTFSBfCa+zGM+z
            IjK7rv1+EadLzZoETE+nxCgN7V8iz4SlM8bB11T0oO1oy5g7WoYblQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xlls984taykl6jyq0f965lyx66qj6e4cg4wqwrfav258c5gpr44qkwuv3w
    encrypted_regex: ^(data|stringData|((?i).*(API_KEY|TOKEN|SECRET|USER|EMAIL|ZONES|DNSNAMES|CLIENTIP).*))$
    lastmodified: "2026-09-14T11:46:28Z"
    mac: ENC[AES256_GCM,data:UqRUWHOYoPtC2A2uSTqBYOAHmfADvdY8GqpM/b8BjRSWAKyja1P6PJneo0EnFhH0easD8Y+tZx2thiXt4JUruADJ2pOyCm1zhhktGrZThCxvZqGlTCHSQWD9xNwOFmqyVEkCHU/uGXZPpQ1MHaqKCvDLY2npkBQ94gxaDibuG4c=,iv:snjiyal16bRW9t1EqlPS7vkQfeYc75mGup6VPh91HIw=,tag:euJ5LjMnw1cLaJHxt4y68g==,type:str]
    version: 3.13.3
