apiVersion: v1
kind: Secret
metadata:
    name: rreading-glassess-secret
stringData:
    #ENC[AES256_GCM,data:7D9XeQ==,iv:KibFXO4LqzWAHpnhFaQYaMgxD87EalfJ2MNlCTtBIao=,tag:0L+3+VUotFmByaGxIFTTIQ==,type:comment]
    HARDCOVER_API_KEY: ENC[AES256_GCM,data:q9/Z07ovp1rOHVwZvhbD5lK21fwpzgVOxCXt3IeDGOIIK0CBBePl5Y2LMs+1fFDjnIl7vltJNU6XGA+yxHUfPtyQ3d038Jk+XGeXvW1AZEsvzGDFdc3M/WxxeFYLsyb1rvssXjkPmhQCwmzhMRut/s86HMkiodSZ4hj7kH8BLeJuYVM7l55Qs5NF3RGV0NYSK8wzu2tDUS+Du5Ipvg22pGm2ActRFiYkvtE5D4B0ReuGUj4EcZm/HH5yW30nSRuCyFtS0bwrZGp6LgPzHIJylSQlrgk5nte5VQ/CAyPu0N1OuPNY7/Z7uCyHovC80JJPOz4ZF+6jW0cT+bJGGWBOIfWi5qz+GuumESKekCOZIQl/sNLHots0kC0B3qxKXnk9OA1+EfdSpD1XiRT3u4xm9JZeV+ZaXZQDY5Y2syILSDY8m0UzPCF9GzfDvetkX18bLXMU/GM+op/plJFoOph6/MLB5U0BK7OuEw0MNYHKYUYpFc9g8e+xMZbHeaH0/rkvgQYwqrSva1vvmi1aKtFdjX9WVCTPwggsLLTikVRE5XisQLGvIFz55fBBe6dSigY0H+7PP95gEt91Z90NNrSMIpUTaqpCNjg3gY6hhXyFRmxVCN/YG2xcDH11qxKU3HgvVFreUskQCj3ybV/fKxn9NPPClf9zqkpOegHL9p01ERvTHYexwYs/kIaloNtxHkquTTrRHPmTkJccTP6i,iv:mTyaudWQ4zX70NlpTUZDaPv8MCHmOVqqYalikWfbksg=,tag:MLXilmCDlfee99aupbtLDA==,type:str]
    #ENC[AES256_GCM,data:K3CUyOI=,iv:+A4bDvvZHSRsc3I+SA7DfvcFigYTlnbGbnHITCrH0LE=,tag:WUdn83zsyyc8MngNkAA52g==,type:comment]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:Usflc70SaS0tGy59MD5fpA==,iv:JnBVqy3dgSbIu27TIziGYSODpCE//I+Ik5beNEQ1dnI=,tag:LMgZqcWLDp6xn+Gu3no+/w==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:mv9vJrxyb0Mu85jTlDgryQ==,iv:WwH6yX7jVCrDjZ9sHsoZhIEoqoc9P/WfijQ5gkf5aRQ=,tag:MpVYd2MJe5galKOetXtGlQ==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:M9LptO6qmfml42g4ZDrMfUviMtmcLwPkXLrhLvDXCcVWkF9mpjTQ0w3GtGE=,iv:v3SBLZkYaVLhfUWEybExaJTAFIqa24uWXR7o77aynjM=,tag:DoG/OFWJPjak3LUYnsDvGA==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:HHJ4eVhratS8NlbARkDLdnEmpE+yT29gED2ZjJuCN46jV4Pjwwk=,iv:NdUjkJ/wi9JUhkouI21/tTjHHEr28fu05TovjU2nGBw=,tag:3HQJNx5XGmnqeaEDNvROdA==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:Fl/O/1qKP3LKI2Q7bBu4OYFwHt8+HJioXTVuu5EfwOZw+BnRtVNptB497Wg=,iv:DwWu1qK6NFPdbFkPOARqje2dFv7gD7pIKvqaHoOQcu8=,tag:iIy3d3UzIP4/OkbDr4pEqQ==,type:str]
sops:
    age:
        - recipient: age1xlls984taykl6jyq0f965lyx66qj6e4cg4wqwrfav258c5gpr44qkwuv3w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyT3k0NSt2eTY3c051SmJ4
            UEdCa3R3bU1xQTBEN3hWdXQzdzlOV0t2T1ZRCmVLZUExUDJMNkJUNnJtTEswL3Jy
            d1VnNnBHNmw0UGZwYVA3cTZLUCttNXcKLS0tIDQvTDhTWk5lNFRmWkliZ3Ewd1ZM
            ajUyb0RRMHd3cGxNR1puNlhjUlJJckEKh/YtfRy+1xDdbsN46ugexiNA2B82MLPl
            WwVy7CEF8O3o7fH7hARb05aet8rYndVsTWBwXK2NCnmSfTG185KuyQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-01T19:37:09Z"
    mac: ENC[AES256_GCM,data:PG7MZWZoeeFxIJyCZREpwo8UI8RevsusfrCXq2s3ABJ7oNCMYjfVN0YIg+lTwE+xLmFXrDEFOh502xCTqb19zHKCd1Hi6QxV3jvlMAquAcwx8sktF55lo6vOUdOnl5DF0OfSsX/eqVDs2OEvBxjt6C4mNzG+oMJZfSiHNCWa8hk=,iv:N9DTzIMOyYJTWbq1Zh4RbTrUOeaYl2rNOqJaduYtfcQ=,tag:YvEhbcMUJlw2fZAi8cUs7A==,type:str]
    encrypted_regex: ^(data|stringData|((?i).*(API_KEY|TOKEN|SECRET|USER|EMAIL|ZONES|DNSNAMES|CLIENTIP).*))$
    version: 3.12.2
