apiVersion: v1
kind: Secret
metadata:
    name: rreading-glasses-secret
stringData:
    HARDCOVER_API_KEY: ENC[AES256_GCM,data:cZnRG0HIR4FdvWjunXZ73gNzeRmVd8vFGXfzO8fZcTlYx0cnOtvM3sOQAclXseSm8uvnp+/8Ux0JZvOJbMq/Hc30PBgD6XqyUdgoTYOzY0ydjZhu+cGZiGfVvyBcjribkPllYRYnFK5cAuKBeG+aphGJN4x0cx90SwKYprb4lg1NWJqhY+G3snWg6U8WKVhH+k0RvhYVpinlEX6dTNiH6UM3Ek3+JyKt/6ANGfIZQLTV9qGXocRRSqnC690x4b2o1QmhmknmIw5AyuKTs3senwzfXiHExTUoS7vt8FVsAIvonYAWHyLI0OVsc4q/QaHD34cy28VHicB7wzfqPmmJUw0eu6ENKMyYNXfsrqgzSWbWoJtngBhQ6U4V7rp3Sde0gCOkUfM6VQ6r+cAinlFjafPe19cVkYCW33lyfxqs4OeLgCnxbqbi8jVVmKKdmUgQm15krdWD8PYD8683NeFZSCOQCmM8J+w3fQrWaRnvwXn77lPSS/17A2UiX8kc1oDMg70Gl7Ee7vfJpgqN84bdDnLwbZkmQILo4baLV+jNjtIcOMPkad6PwSAV2szRFcv8mWAZpiCcnA2F7oQHIJQb9JFExkmlSu3BaIEWrW4u1gElzZ/6moKqSh0Elvdpja2AwZYDmjTagcyfGUrx+Wh3BciGZqpb9a0ptWiQcd+MDC9A6m7WK0/1jDW+ioKY8TlEGAPgvXalGsDCxBva,iv:E5IO+jfzeIfXNIX2UApaXL9EhpSyAmtI5WlBpfi+8Hk=,tag:NXCULBPB9sQbJbTmw3Cpyw==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:oMZB5aHuaXcEDariRvYg3w==,iv:8uzqEkBqGqmW3qZsHeJHxU1YXIZI0s5YTVXwyh/s+Fs=,tag:0RxIRtJaWC71ePnrWm/GJg==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:jYUiIuqLCWAGSED9MukN,iv:XOUyQpV5PJJq2tx+1ntImlxB7P1JE/6bTZupijYFO2k=,tag:XziBjJTo/EJqz8y7xbMhMg==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:raFjnIg2kfNzkYaxSuj4upqSJfIhMYYCMICzbt+NoZF2tcruSVvOK72tZKU=,iv:Is4VilswhswxGw3+HsbEM7i8z0nGOu0DCcFYX1lkq1E=,tag:h9ehk5/tANfVId1ZD+v5tw==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:fIONlHYGWKWibChZEkbR3LDlbRyrmod+4u+2+ZI/xcZKtnPnhNON+dH09GU=,iv:lJtiP7pkhlr7YDHbaqcawf2zKhpDn9N0aLcAvHDO/6Y=,tag:bOE9cgYS/kpUUUJ6ehnDyQ==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:0ew3LhloSOKrJeu9cFqWXw==,iv:5pBF9Gc6yZTGFnAbijoeosqGu9TcPas0j5a4NGuCVGo=,tag:0+DcAMuY2VS5jM4+Ov2gwQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvelJYN1hIWDNLeE00K0pP
            M3RtS1lNNDgrUFFsQXo2QlRUb3RnN3o1VFVzCk94NFRvanZoWGhEbUNyQ2ZDZVJw
            WnJLdUtyWVpDNmdLQmN6NGVpbE1raW8KLS0tIFplZHpScXFVdUtQWGtJMlBtUnJv
            TXN0dzJ1aXBKSkJxRFdsenpoblA3bDQKnlrk9ewHk2SmmL2wY9vAcNHGOXLxWmv7
            2zx99P0GJDV5Y/A9ParTJi8GROQhH9PxA8dZUt+4GXSAgf15B8Jk5w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xlls984taykl6jyq0f965lyx66qj6e4cg4wqwrfav258c5gpr44qkwuv3w
    encrypted_regex: ^(data|stringData|((?i).*(API_KEY|TOKEN|SECRET|USER|EMAIL|ZONES|DNSNAMES|CLIENTIP).*))$
    lastmodified: "2026-05-28T21:06:15Z"
    mac: ENC[AES256_GCM,data:0+JTve0yakgD7b0D6VSW2VEeRMRBOXZhlN/CNWdf8tu2Nclv9Ti6JSPqtI+sNK6rSoTHjxu0EUrPZKtJWs6QKC587fP55aQOcotYtHqN3beZ+xLR0GfeLyawq7mQaw/p2s4Qi4TXWjzJ/JNRiLtndW4rWciBOZtI26BZ6fEYyTc=,iv:6xbtVxzhK1DyvQ6O5+lS6TA3tDUh2eHC2GLRKk1fLYc=,tag:M81dnZQSlSKO3nmhPM+Oog==,type:str]
    version: 3.13.1
