apiVersion: v1
kind: Service
metadata:
  name: cert-manager-metrics
  namespace: cert-manager
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/component: controller
spec:
  selector:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: cert-manager-controller # Try avoiding overlap
  ports:
    - name: http-metrics
      port: 9402
      targetPort: http-metrics
