apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
    name: homelab-wildcard-cert
    namespace: cert-manager
spec:
    secretName: ENC[AES256_GCM,data:N6Gljt5mdufRO0myIxjfqnbOQSA=,iv:VkqqB3ViLwxN3LgSIKUE4kbJyDm40UY+hRhKyGA/1q8=,tag:jhblSP4MbSy4piEvccHcwQ==,type:str]
    issuerRef:
        name: letsencrypt-dns-namecheap
        kind: ClusterIssuer
    dnsNames:
        - ENC[AES256_GCM,data:oMmdd/2TU5tUZWIpsOXa5YnxAGt+J3HJopA=,iv:5l70Pdl9Ct881AEnz4qg0T9G7hH57M4nhA1vCNuBduc=,tag:gzEuMGFyZjJJ6vMBJM4n1A==,type:str]
        - ENC[AES256_GCM,data:BALeEo44CnIMqNrqBX9NvjZsqbwta2Uk,iv:V677/3HRB15KUVhtvB+vqy9VC+GE0bYeitrVjl/WEEw=,tag:+6zWRlashV4mT3FNRm0qZQ==,type:str]
sops:
    age:
        - recipient: age1xlls984taykl6jyq0f965lyx66qj6e4cg4wqwrfav258c5gpr44qkwuv3w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJN0UzY3VZdUw3SVhTY0tP
            YXBSbWJrOUQ0aXdTTkxENTFiSW8xOVpFREM0ClJXaXlXUHNpVlV3Qlk1d0FST2hn
            Y2EyR08wV0VWZXd4dHVMVXpaUmpGTGsKLS0tIFE0K2RHVk1wVWxZNk93cTNCSEh6
            ZEE2U01LZE5ZMEJubXpqNVNuY3d5NFkKqJ0wJPA+3SrJzpMmUy8/4VlRTGEhEopF
            zKQs8Lr2y/0T0eK5WiPB8m/JWLFmEQlzYz1lADOlddHX60lTjz1bJQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-12T14:37:11Z"
    mac: ENC[AES256_GCM,data:CH0QemnnRhKYE/0Fr8uJwTVvTzL1Ug05ejXSOUL3qYigx7Z3VQZ03vODNaI108Iy/bWoGcCoZ7JF8WKgcIsS9HITQRwzOlErhJbeGUP0rYoBNYPzjrIJshO9Us+O5Mi3nFFEw+3taiYfaD3u1y+8ThVUJ2657+jw2Sw7n0AyMac=,iv:ieAwrRen6ByJo+qTCX7nBsFlqtq/RdINB0Ztn/wlUYc=,tag:TLHqfJlwTs91PwPFt9OsBA==,type:str]
    encrypted_regex: ^(data|stringData|((?i).*(API_KEY|TOKEN|SECRET|USER|EMAIL|ZONES|DNSNAMES|CLIENTIP).*))$
    version: 3.10.2
