---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-metrics-k8s-stack
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: victoria-metrics-k8s-stack
      version: "0.56.0"
      sourceRef:
        kind: HelmRepository
        name: victoriametrics
        namespace: flux-system
  values:
    # Disable components we don't need yet to save resources
    vmalert:
      enabled: false
    vmalertmanager:
      enabled: false
    vmsingle:
      persistentVolume:
        size: 10Gi
    vmagent:
      # This enables scraping of ServiceMonitors, which is the standard way
      # applications expose their Prometheus metrics.
      spec:
        serviceMonitorScrapeInterval: 1m
        serviceMonitorSelector: {}
        podMonitorSelector: {}
