---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-metrics-k8s-stack
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: victoria-metrics-k8s-stack
      version: "0.56.0"
      sourceRef:
        kind: HelmRepository
        name: victoriametrics
        namespace: flux-system
  values:
    # Disable components we don't need yet to save resources
    vmalert:
      enabled: false
    vmalertmanager:
      enabled: false
    vmsingle:
      extraArgs:
        search.enableLabelAPI: "true"

      storage:
        volumeClaimTemplate:
          spec:
            accessModes: ["ReadWriteOnce"]
            storageClassName: longhorn
            resources:
              requests:
                storage: 10Gi

    vmagent:
      spec:
        # These two new blocks tell vmagent to look for monitors in ALL namespaces.
        # An empty selector {} means "no restrictions".
        serviceMonitorNamespaceSelector: {}
        podMonitorNamespaceSelector: {}

        # These selectors tell vmagent to use ALL monitors it finds within those namespaces.
        serviceMonitorSelector: {}
        podMonitorSelector: {}
