apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    # This allows pods like node-exporter to run with the host access they need.
    pod-security.kubernetes.io/enforce: privileged
