---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: excalidraw
spec:
  interval: 1h
  components:
    - ../../../components/fa
  path: ./infrastructure/apps/selfhosted/excalidraw/app
  postBuild:
    substitute:
      APP: "excalidraw"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: selfhosted
  wait: false
