apiVersion: v1
kind: Secret
metadata:
    name: gatus-webhooks
stringData:
    DISCORD_WEBHOOK: ENC[AES256_GCM,data:8vE4cyJFQmXhEZyNlgBwj+F7PjVkgPLPbuO2TTN0S3uPgdXq8xzgfOZehSfexu4efm6Mj+qIi8QXrVqDoZ2ryji9j9Mg9A0uXPgeVKfYa+FA4YDWSmM1pOYN0VJlIWAPW9YvZ16IWNHFVPby/Hzki72VrkJwKTcVtw==,iv:WWDGwoR1EbTchFjOW4eugq/eq+kRjomO00Pmn8b3Mck=,tag:NmpkiK3K1PBeUm0JH1gL8w==,type:str]
sops:
    age:
        - recipient: age1xlls984taykl6jyq0f965lyx66qj6e4cg4wqwrfav258c5gpr44qkwuv3w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXZVE3OGc2NnNjL0VxcE50
            OVY4V2xsd1pwV1lCaC9kenNtdDFkMTl4MHpjCmR0N0ZaVXBHWTVjVndFcklIYjFO
            azVSdDBQSjdEOUpiZ25UbUdhOEg3d0UKLS0tIGkrRW1KY0RFRG9tSGMxci9IbVo1
            K1ZUSFdGVklrWWlGSGFNMzBuUUMrNXMKoKC21y10eYvOzCOFZirGY+EYOoKknr39
            RuaDN+RVJuGLiPnFhYZ4qAawpfgHAqCXA9j8YesMc9kcvnjeS7rtFw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-05T23:43:40Z"
    mac: ENC[AES256_GCM,data:2EwgGShjLj+peega8nU6Zetonj4fKnrr7vuEGKjybbHwj5VU45CigN7c7fU91I5RlFGOGHqbRLv6w42d4179u9STd3m3MYjJnbs+lzR31jXJBZbd2IsKobho5IU/+oCq8JbBZ14BI9vcjFCq6WE7nhP5q/uw1Kk0Z2xscbEqF3o=,iv:lRs44LiZoZBEGHotYHcNb4h/PThBuLSGmAZP82PsWCM=,tag:V2OTR7SPZPuo0SJj9bOTZQ==,type:str]
    encrypted_regex: ^(data|stringData|((?i).*(API_KEY|TOKEN|SECRET|USER|EMAIL|ZONES|DNSNAMES|CLIENTIP).*))$
    version: 3.10.2
