apiVersion: v1
kind: Secret
metadata:
    name: gatus-webhooks
stringData:
    DISCORD_WEBHOOK: ENC[AES256_GCM,data:VmltYX/J8ttjQP6WBCo4EFVA9Yn3EdWFUwylyGwhVD1UK5TYpXMUhWvQvxc54FZ6HuHrH+NopIV0JGt3/X4yKHPwCZIxPJynv0lUkKWGj3ZeLIA2gzhmNiyeFUJp2fNGL8OJKL9mnFC3yfLRd03s9jeFNfJWIPRnQg==,iv:yNOW89TIIiSMx4FmpRuMBiCjno/geslK7TdCqGMzhkU=,tag:fnM+cadnjzPJSHQTlHnGPQ==,type:str]
    MULTISCROBBLER_BASIC_AUTH: ENC[AES256_GCM,data:eY4XqZXaw093Ld2eLa3KC7/n4ehLnu6arKTE6A==,iv:7VvXw+EWBmtfv5NVbJlHrCEpUQFqSvdFza+D3lq/Ruw=,tag:fYY0XY+U+75jPwGBCWO9sQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwdXlsQVdWc2RGM3lPQUt2
            MkluNndqcS9Bbi8yY0t2ZFhldVo3NGYzdUVBCjQrVHJpU1RDZDdDTmQ4REdLdUpS
            YWRoc1hveTJjSW8yVHJzZzFGQUNXcVUKLS0tIG1tRERyUnI4NVVzMWxLejFQd2pS
            R2tmbHZNcUN1N1lvNlNPcVYwb0d2ZXcKb47fDBWsYuajDrooKn2N3DjMxy+PN1U/
            l28nMFNVbKWh2ag7l+C4LxWB63geliA7kmoNnJ6RRelq7xUXsH2aew==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xlls984taykl6jyq0f965lyx66qj6e4cg4wqwrfav258c5gpr44qkwuv3w
    encrypted_regex: ^(data|stringData|((?i).*(API_KEY|TOKEN|SECRET|USER|EMAIL|ZONES|DNSNAMES|CLIENTIP).*))$
    lastmodified: "2026-09-13T17:25:59Z"
    mac: ENC[AES256_GCM,data:woI6JRCZVAjlVTPYv0bK6O5DSULITEqRRccbp/iwoeV67RTMyS7g7HSYJ0d2/FPpaA46L5mEWAv+uxIAmGjpY2DDs8CXcptwVl3VhIEQLe/C5t0YrTWP14B2CDrSlOpjSzqmSkHPKUgXaSMoV+e1RXhMOw/S96w/15XvQH2z1lw=,iv:5+Mf3s85F7xC+JV9LX6uun77v1oZOSFkIyIJIyHykus=,tag:r/ra7jO/pr7FM8Z+5NFiOw==,type:str]
    version: 3.13.3
