apiVersion: v1
kind: Secret
metadata:
    name: gatus-webhooks
stringData:
    DISCORD_WEBHOOK: ENC[AES256_GCM,data:V6ye2aynA7X5W9v9NRjKya/lq7uVP+H9qcxZ9hgR9Wi1J90FofBeEU8ZX+Tp6QrXe0sdbo/yFDsFza9HAYwDoiu2lm7CeoS+fReg4BuHfofIup3ANemyKEzBAw4kFzCfu9EZo0xeyDVj5wz7NrC+yaSorwzmqohSlQ==,iv:VjD+tGl2vEsnP7VSNQIvHii+SoVht1+jTN02rGp6wiU=,tag:akRK2WYvExUx4zdFavdUpw==,type:str]
    MULTISCROBBLER_USER: ENC[AES256_GCM,data:v8LZA7xATQM=,iv:5uf7cSgubRF3ZWJKJE0BIlHUIxMkBlFiRTrA+coBpnY=,tag:SCeEuFuY0W0P7Fz7uapVvA==,type:str]
    MULTISCROBBLER_PASSWORD: ENC[AES256_GCM,data:obGztfbM3arKEg==,iv:uUoKPNjTSLyomoUpEiD7mp/zVce2Pw2WeenT2Hwp/Mw=,tag:+EmoAb3UUYG151pbp3bXBQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJeit1MW84UUxKYjhhT0lM
            VFZxU2RpZEMzT2dVZ0ozNEFHRXJqNndqOHk4CndIck9mbW0vVVdMWjRlcWhlcnU0
            RHNLZE4rY29iUjRhT1VYTEFyV0E5UUEKLS0tIFUzL09tbmdiRC9yeXZrdTZKaTFK
            THgzbXNlSnc0aHVwSEw5TmFGaVNqYzQKXxeXVcebl9/4GJl652UcT3PZapJP9YG3
            XmKByvqKZewxKNAhx1GrXa+yaDOvf8BqH8Si0B5ua5xtwVMnLRVUAg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xlls984taykl6jyq0f965lyx66qj6e4cg4wqwrfav258c5gpr44qkwuv3w
    encrypted_regex: ^(data|stringData|((?i).*(API_KEY|TOKEN|SECRET|USER|EMAIL|ZONES|DNSNAMES|CLIENTIP).*))$
    lastmodified: "2026-09-13T17:07:59Z"
    mac: ENC[AES256_GCM,data:R9bBBg0IHDIF8ASzbF3SKdSJzAI6P4MzpWiX0+7SwAytWrZOGqwNz3LgUgDJaQx4E4Y3JxmTlKgVK0e2tjRg84LMeNKa7przrRCmJ810lPdb2f8sIyJR8NcrZRpZGKvUsHyv7sTYD5xqqMgKReoBqehny+ODqh2QFKHoR6TJTeg=,iv:PiZhzBQECkSYjQiM2KmCuUJpvQEEr5rWS8Bwnbhwq/o=,tag:sbjpdwEFgJSfN0F/MqOfBg==,type:str]
    version: 3.13.3
