---
# yaml-language-server: $schema=https://kubernetes-schemas.nerdz.cloud/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app qbittorrent
spec:
  targetNamespace: media-center
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./infrastructure/apps/media-center/qbit/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
  interval: 1h
  postBuild:
    substitute:
      APP: *app
