---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: capacitor
spec:
  interval: 5m
  ref:
    tag: v0.4.8
  url: oci://ghcr.io/gimlet-io/capacitor-manifests
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: capacitor
  namespace: flux-system
spec:
  interval: 10m
  path: "./"
  prune: true
  sourceRef:
    kind: OCIRepository
    name: capacitor
  timeout: 2m
