---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
# capacitor-source.yaml
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: capacitor
spec:
  interval: 5m
  ref:
    tag: v0.4.8
  url: oci://ghcr.io/gimlet-io/capacitor-manifests
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: capacitor
  namespace: flux-system
spec:
  interval: 10m
  targetNamespace: flux-system
  sourceRef:
    kind: OCIRepository
    name: capacitor
  path: ./ # root of the artifact
  prune: true
  timeout: 2m
  wait: true
