apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tempo
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: tempo
      version: "1.23.2"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    tempo:
      securityContext:
        fsGroup: 472
        runAsGroup: 472
        runAsUser: 472
        runAsNonRoot: true

      containerSecurityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        readOnlyRootFilesystem: true

      storage:
        trace:
          backend: local
          local:
            path: /var/tempo/traces

      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 1000m
          memory: 1Gi

    persistence:
      enabled: true
      storageClassName: longhorn
      size: 10Gi

    distributor:
      enabled: false
    ingester:
      enabled: false
    querier:
      enabled: false
    queryFrontend:
      enabled: false
    compactor:
      enabled: false
