apiVersion: v1
kind: Secret
metadata:
    name: towonel-secret
stringData:
    TOWONEL_INVITE_TOKEN: ENC[AES256_GCM,data:TRM2MSi7suICecOd05x4g0PWnMOg0kmm6gQrgeLGaAFciKDF/LeZhykLStdmQQH5QOgQr/GPGLxuLHNlzEpY/x4HYW+1IpyIOypvxsJORY2JwhUCAdoV/OtQVXwDiTPtEal1hEXsvuhR9LugGKSw75dKdckZ+1VKwSXOsgh7OX75iGaT6AsZDLHajCWqvJJN9S5E2no3eUWA3YvQJv+IILK1mx3+Dg==,iv:7DvO1iSJjZ8Z6ww6T9I9tEDTivGrbbuJGIvvtr8t938=,tag:9se5ZHlnQOrqNsCbiWKFfA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxRjNYSmNkdHhKajdITVhv
            TC9ER0Ura0VGRTZLVkdnYmpnRERQN3dKZWd3CmxYVzFoc0Q2YTBpNmtWVkJ2K2lq
            bGg2T1d5bWVkdEJJOGc5SUs3TVRLNWsKLS0tIHdJVG1pckZLZXRwcElGV3hneDV6
            UXZ5Z2N6bUxHN1N1U1pyRTFHL1ZSM2sKmFQDvB4v1zVi8BttCowsH7el96RIN78A
            mzGhipBPhvccMtNsvAJVCONtYTOLO3utCPAku0Q7F7wr+wU4sVQKmw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xlls984taykl6jyq0f965lyx66qj6e4cg4wqwrfav258c5gpr44qkwuv3w
    encrypted_regex: ^(data|stringData|((?i).*(API_KEY|TOKEN|SECRET|USER|EMAIL|ZONES|DNSNAMES|CLIENTIP).*))$
    lastmodified: "2026-07-25T16:47:46Z"
    mac: ENC[AES256_GCM,data:TjBox5IcHKONiJ9uoxiWOjxqSdEKwHsHGvGUXQ/9S8mVMwWgCmxNUhw4T3c4OCJdsnxFIWWflzTGfcYH0eEIBkE1robVFINj3jShtvFwFFhe3KJmiJ4qD4YWw6jAaO7xoezxAetNOTdJ+fvyCEX/ge5YseBOaxe6CRdZw2yBuVA=,iv:T6vn8HlHZDb3xkP9xGnX90HCgEmH03Q1g3dD858WkSc=,tag:G0m7Df+8qRG9Gji+hWc8cw==,type:str]
    version: 3.13.3
