apiVersion: v1
kind: Secret
metadata:
    name: towonel-secret
stringData:
    TOWONEL_INVITE_TOKEN: ENC[AES256_GCM,data:9bhH4w2A6hsYqsWBa1HQjTePpBCFOOktzOKpQfC6zCWGF77J7mgWAjKHNNmPeI6UlUGSm/auJvt2J9wx6vU6NfpXg+LxOpzN8CV7Eo9r0HXRZOcNC7NtHvk/jDlqKncMs9mNXd/ElUNGkuXRgPF3n17sBgr5HZ6J57WGohMcafOhmtFqJpglRBEnoaHtrhiuCIchTv/a0DfrUZw=,iv:X2pfCdcXyeWv0S4JagxIGTzpzV8XgzyrsWrOSFxfVtA=,tag:YRUp/55GRN1XENr4Ultvfg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMWEJkRnAzREE1cDZIanRj
            aE1yNTdwY2Y0L3MydTZHL2FwVHRRd0lzRDFrCkNHa0Y1R2E4R29PVkcyMnZKd3dr
            YWc2MlhhQzQ3S3NvMnBJbTNxaklwUHcKLS0tIFVzdjRWUmRaQWdiRUthcnFnRm1v
            S1A1aFdKU08wMHJwa1JleHNvWXhPTFEK8SRmK/Fbq7ucVwv1nEIb7vEvgmG7OyTY
            v5NvZklzKWy1SyS1wvqYIRgkK/3l6thstDTzZdiVJI8rejBtiRh/6A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xlls984taykl6jyq0f965lyx66qj6e4cg4wqwrfav258c5gpr44qkwuv3w
    encrypted_regex: ^(data|stringData|((?i).*(API_KEY|TOKEN|SECRET|USER|EMAIL|ZONES|DNSNAMES|CLIENTIP).*))$
    lastmodified: "2026-07-25T14:57:00Z"
    mac: ENC[AES256_GCM,data:V3PNVVAOb/lDd/Rtheiej2MjS8Xd3IIJOe4y1zZWusncKRK+HP3offKAqhv5Q4ccfVWP6PWEd2eR1xRUJuSBApwEZA3mh0fRO2d1Lfmo8pJKakI3yBIplCKGMKjAq7Q+IlQPcNlNdr26rQxewQZ/PVmoOzUdb5S65IBu5F1z52o=,iv:u2KTKhWfdug8Q0lgf5iUZBaFQdnQLE0/siXDa4uWMF4=,tag:ETpazGiEe6WkJBxbdHWu/Q==,type:str]
    version: 3.13.3
