apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: capacitor-dashboard
  namespace: capacitor
spec:
  parentRefs:
    - name: main-gateway
      namespace: metallb-system
  hostnames:
    - "capacitor.homelab.taylandogan.info"
  rules:
    - backendRefs:
        - name: capacitor-dashboard
          port: 80