apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: monitoring
  labels:
    grafana_datasource: "1"
data:
  datasources.yaml: |-
    apiVersion: 1
    datasources:
      - name: VictoriaMetrics
        type: prometheus
        access: proxy
        # This is the correct URL for the vmsingle service
        url: http://vmsingle-victoria-metrics-k8s-stack.monitoring.svc.cluster.local:8429/prometheus
        isDefault: true
      - name: Loki
        type: loki
        access: proxy
        url: http://loki.monitoring.svc.cluster.local:3100
      - name: Tempo
        type: tempo
        access: proxy
        url: http://tempo.monitoring.svc.cluster.local:3200
  dashboardproviders.yaml: |-
    apiVersion: 1
    providers:
      - name: default
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards
  dashboards: |-
    cert-manager:
      # renovate: depName="Cert-manager-Kubernetes
      gnetId: 20842
      revision: 3
      datasource: VictoriaMetrics
    cert-manager2:
      # renovate: depName="cert-manager2"
      gnetId: 22184
      revision: 3
      datasource: VictoriaMetrics
    coredns:
      # renovate: depName="CoreDNS"
      gnetId: 14981
      revision: 2
      datasource: VictoriaMetrics
    envoy:
      # renovate: depName="Envoy Proxy Monitoring gRPC"
      gnetId: 23239
      revision: 1
      datasource: VictoriaMetrics
    kubernetes-api-server:
      # renovate: depName="Kubernetes / System / API Server"
      gnetId: 15761
      revision: 19
      datasource: VictoriaMetrics
    kubernetes-coredns:
      # renovate: depName="Kubernetes / System / CoreDNS"
      gnetId: 15762
      revision: 20
      datasource: VictoriaMetrics
    kubernetes-global:
      # renovate: depName="Kubernetes / Views / Global"
      gnetId: 15757
      revision: 43
      datasource: VictoriaMetrics
    kubernetes-namespaces:
      # renovate: depName="Kubernetes / Views / Namespaces"
      gnetId: 15758
      revision: 42
      datasource: VictoriaMetrics
    kubernetes-nodes:
      # renovate: depName="Kubernetes / Views / Nodes"
      gnetId: 15759
      revision: 37
      datasource: VictoriaMetrics
    kubernetes-pods:
      # renovate: depName="Kubernetes / Views / Pods"
      gnetId: 15760
      revision: 36
      datasource: VictoriaMetrics
    kubernetes-volumes:
      # renovate: depName="K8s / Storage / Volumes / Cluster"
      gnetId: 11454
      revision: 14
      datasource: VictoriaMetrics
    node-exporter-full:
      # renovate: depName="Node Exporter Full"
      gnetId: 1860
      revision: 41
      datasource: VictoriaMetrics
    k8s-dashboard:
      # renovate: depName="K8S Dashboard"
      gnetId: 15661
      revision: 2
      datasource: VictoriaMetrics
    loki-kubernetes-logs:
      # renovate: depName="Loki Kubernetes Logs"
      gnetId: 15141
      revision: 1
      datasource: Loki
